### ISSUE TITLE
After renaming an api and trying to creating an api with the same gives an error 

### ISSUE THREAD

**Issue by poorna2152** [wso2/mi-vscode#100]
**Description:**
If we create an API named `foo` and later rename it to `foz`, when trying to create an API with the name `foo` again shows an error in the form, `An artifact with same name already exists`.

<img width="1512" alt="Screenshot 2024-07-16 at 14 25 36" src="https://github.com/user-attachments/assets/d1e6d085-930f-42df-b0d4-400a58737c96">

**Comment by ChinthakaJ98** [comment]
This is a known issue and it exists for all artifacts as the content in the artifact.xml file is getting updated only at the artifact creation by adding its details. Therefore we will keep track on this and come up with a solution in a later release at the earliest which will update the artifact.xml file accordingly when updating and deleting artifacts.

**Comment by ChinthakaJ98** [comment]
Closing this issue as a fix was done to rename the artifact file name as well when the artifact name is changed. A separate issue(https://github.com/wso2/mi-vscode/issues/132) was created to keep track of the other aforementioned concern which is the requirement to update the artifact.xml file when the name of an artifact in the registry is being changed.
