### ISSUE TITLE
When API version is set, some key functionality is not working

### ISSUE THREAD

**Issue by isudana** [wso2/mi-vscode#101]
**Description:**
When we configure version-related parameters in the API, the following functionality breaks,

- TryIt
- Debugging

We need to think of how this happens and is there any other functions that can break and fix them all.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
MI extension for VS Code v0.9.24071508 (pre-release)

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
- Create an API and set versioning-related parameters to nondefault values.
- Try TryIT and mediation debugging.

**Related Issues:**

**Comment by sachiniSam** [comment]
In the debugger logs we get `{"command-response":"failed","failed-reason":"api not found"}` for the breakpoint info request we send to the MI server. seems there is an issue with the breakpoint info we get from the LS.

**Comment by sachiniSam** [comment]
It seems the api version is missing in the LS call getAvailableResources(). But the management api captures the api version along with the name, Will we need to maintain a similar naming format in the server and LS
