### ISSUE TITLE
'org.apache.synapse.SynapseException' when adding a PropertyGroup mediator

### ISSUE THREAD

**Issue by gabilang** [wso2/mi-vscode#104]
**Description:**

Adding a property group mediator using the graphical view gives `org.apache.synapse.SynapseException: group is only allowed when a pattern is specified` when running the MI server. 
It seems the group is specified in the synapse xml script by default even though the string pattern is not specified.  
```xml
<?xml version="1.0" encoding="UTF-8"?>
    <api context="/test" name="TestAPI" xmlns="http://ws.apache.org/ns/synapse">
	<resource methods="GET" uri-template="/testresource">
		<inSequence>
			<propertyGroup>
				<property name="username" scope="default" type="STRING" expression="json-eval($.username)" action="set" group="0"/>
				<property name="password" scope="default" type="STRING" expression="json-eval($.password)" action="set" group="0"/>
			</propertyGroup>
		</inSequence>
		<faultSequence>
		</faultSequence>
	</resource>
</api>
```
Graphical view of artifacts used to generate the above Xml configuration:
<img width="1042" alt="Screenshot 2024-07-16 at 20 54 49" src="https://github.com/user-attachments/assets/bc9dafdc-59a7-4da8-bfa4-13f12c705aff">

Removing the `group` config from the above scripts allows the server to start without the above error. 
If the `Value String Pattern` is not provided the `Value String Capturing Group` should be omitted.   

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by gigara** [comment]
The latest pre-release v0.9.24072507 has resolved the issue. Please reopen if the problem persists.
