### ISSUE TITLE
Open Graphical View button is not working for artifacts with forms

### ISSUE THREAD

**Issue by thuva9872** [wso2/mi-vscode#105]
**Description:**
The `Open Graphical View` button is not working for artifacts that doesn't have diagram. This should open the form for these artifacts.

<img width="1050" alt="image" src="https://github.com/user-attachments/assets/41b79b9e-4e30-4f66-a30d-e9e9af795b18">  

Steps to reproduce:
1. Create an endpoint.
2. Open it in the xml view.
3. Click the `Open Graphical View` button.

**Comment by gigara** [comment]
The latest pre-release v0.9.24072507 has resolved the issue. Please reopen if the problem persists.
