### ISSUE TITLE
Minimized MI Overview does not maintain proper layout

### ISSUE THREAD

**Issue by chathuranga-jayanath-99** [wso2/mi-vscode#108]
**Description:**
When the MI Overview is minimized, the text within the MI Overview becomes very close as illustrated below.
<img width="671" alt="text-overlapped-mi-overview" src="https://github.com/user-attachments/assets/be386017-ef6d-4655-8888-6064ed9ed0ed">

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    
v0.9.24071508

**Steps to reproduce:**
1. Create a project. 
2. Create an API.
3. Run the project. 
4. Open MI Overview.
5. Minimize the window. 

**Related Issues:**

**Comment by ChinthakaJ98** [comment]
This issue will be further tracked via https://github.com/wso2/mi-vscode/issues/17 as they highlight a similar concern.
