### ISSUE TITLE
Salesforcerest Connector: Update view does not display field values after connection creation

### ISSUE THREAD

**Issue by chathuranga-jayanath-99** [wso2/mi-vscode#109]
**Description:**
After creating a Salesforcerest Connector connection, when navigating to the update view to modify a previously added field value, the update form appears empty. None of the previously added values are displayed in the update form. However, the source view of the connection correctly shows the previously added values.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
v0.9.24071508

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
1. Create a new project.
2. Goto `Local Entries` -> `Connections`. Create a new connection. 
3. Again goto `Local Entries` -> `Connections` -> [your created connection]. 
4. Compare the appeared form with the source file of the connection. 

**Related Issues:**

**Comment by kaumini** [comment]
The latest release v1.0.4 has resolved the issue. Please reopen if the problem persists.
