### ISSUE TITLE
XML becomes malformed when auto-format is enabled in VSCode

### ISSUE THREAD

**Issue by GDLMadushanka** [wso2/mi-vscode#111]
**Description:**
When the auto-format option is enabled in VSCode, auto-formatting from VSCode and MI plugin get crashed and provide a malformed XML as a result. 
<img width="558" alt="Screenshot 2024-07-18 at 09 37 00" src="https://github.com/user-attachments/assets/0e079eb3-bd7b-41d3-885a-2104d2144813">

Here "min" becomes "in"
<img width="1116" alt="Screenshot 2024-07-18 at 09 37 45" src="https://github.com/user-attachments/assets/982142d2-8784-455e-8ca5-cf68c763d764">

**Affected Product Version:**
micro-integrator-0.9.24071713

**Steps to reproduce:**
Enable auto formatting in VSCode
Create an API, add an aggregate mediator and save.

**Comment by hevayo** [comment]
Fixed with v0.9.24072507
