### ISSUE TITLE
Data service does not have the option to creating a query 

### ISSUE THREAD

**Issue by gabilang** [wso2/mi-vscode#117]
**Description:**

Integration studio offers a way to create queries when configure data services (refer: https://mi.docs.wso2.com/en/4.3.0/develop/creating-artifacts/data-services/creating-data-services/#creating-a-query).
It seems the above option is not available in the mi-vscode extension. 

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by ChinthakaJ98** [comment]
Hi @gabilang,

The option to create a query is given in the diagram view of the resource.

**Comment by gabilang** [comment]
https://mi.docs.wso2.com/en/4.3.0/develop/creating-artifacts/data-services/creating-data-services/#generate-data-service-from-a-datasource Is this feature still there in the vs-code extension? Can we create a data service directly from an existing datasource?

**Comment by ChinthakaJ98** [comment]
Hi @gabilang,

Not at the moment, but we need to work on that. Could you please create an issue for this so that we can keep track and deliver the feature at the earliest.

**Comment by gabilang** [comment]
Created an [issue](https://github.com/wso2/mi-vscode/issues/122) to track the feature for creating data services from the existing datasources. Hence closing this.
