### ISSUE TITLE
On Downloading new connector the form is not generated

### ISSUE THREAD

**Issue by kaumini** [wso2/mi-vscode#120]
**Description:**
On adding new connector, the ls notifies as "not success Failed to add connector. Corrupted connector file."

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by kaumini** [comment]
Adding an inbound connector to the connector folder has caused this by identifying as a corrupted connector. Once inbound connector addition is supported this issue will be fixed.

**Comment by thuva9872** [comment]
The latest release v1.0.1 has resolved the issue. Please reopen if the problem persists.
