### ISSUE TITLE
Extension fails to start when overview page is closed before loading

### ISSUE THREAD

**Issue by thuva9872** [wso2/mi-vscode#121]
**Description:**
When the overview page is closed while the extension is loading, the extension fails to start.
<img width="850" alt="image" src="https://github.com/user-attachments/assets/03552a59-b274-4cb4-b76b-168ef6c93460">

**Steps to reproduce:**
1. Open an integration project.
2. Close the overview page before the extension starts.

**Comment by gigara** [comment]
This issue cannot be reproduced with the latest v.1.1.0 version.
