### ISSUE TITLE
Data mapper deletion does not work correctly

### ISSUE THREAD

**Issue by chathuranga-jayanath-99** [wso2/mi-vscode#123]
**Description:**
After adding a data mapper to a sequence, an entry is created in the `artifacts.xml` file located in the directory `src/main/wso2mi/resources/registry` in the source view. However, when the data mapper is deleted from the project explorer in the micro integrator, the corresponding entry in `artifacts.xml` is not removed.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
v0.9.24071813

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
1. Create a project. 
2. Add an API. 
3. Add a resource.
4. Add a data mapper to the sequence of the resource. 
5. Delete the data mapper from the micro integrator project explorer. 
6. Go to source view and look into the `src/main/wso2mi/resources/registry/artifacts.xml` file content.

**Related Issues:**

**Comment by arunans23** [comment]
Fixed in version 1.1.0.
