### ISSUE TITLE
Inbound endpoint Form doesn't work correctly. 

### ISSUE THREAD

**Issue by KalinduGandara** [wso2/mi-vscode#124]
**Description:**
When open an Inbound endpoint form values are not been filled. 

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
Follow this https://mi.docs.wso2.com/en/4.3.0/learn/examples/inbound-endpoint-examples/inbound-endpoint-kafka/#synapse-configuration
1. Paste inbound endpoint xml. 
2. Open form again.

**Related Issues:**

**Comment by KalinduGandara** [comment]
when property `protocol="kafka"` is missing this issue happened.

**Comment by thuva9872** [comment]
The latest pre-release v1.0.1 has resolved the issue. Please reopen if the problem persists.
