### ISSUE TITLE
When adding a schema that contains an array to the data mapper, the array is not identified. 

### ISSUE THREAD

**Issue by chathuranga-jayanath-99** [wso2/mi-vscode#125]
**Description:**
When creating a data mapper using a JSON file that contains an array to generate the schema, the array is not identified; only fields are recognized.

Tested json file content. 
```json
[
  {
    "name": "John Doe",
    "description": "A software engineer from California."
  },
  {
    "name": "Jane Smith",
    "description": "A graphic designer based in New York."
  },
  {
    "name": "Alice Johnson",
    "description": "A freelance writer and editor."
  },
  {
    "name": "Bob Brown",
    "description": "A project manager with experience in IT services."
  }
]
```

View of the schema in data mapper. 
<img width="310" alt="Screenshot 2024-07-22 at 11 25 08" src="https://github.com/user-attachments/assets/1ea09a63-c920-4a8f-8c9d-9639791cb8ce">

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
v0.9.24071813

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by madushajg** [comment]
@chathuranga-jayanath-99 Could you please upgrade the vsix to `v1.0.0` and try? Let us know know if the issue persists.

**Comment by arunans23** [comment]
This is fixed with https://github.com/wso2/maven-tools/pull/132
