### ISSUE TITLE
Current pre-release(v0.9.24071803) does not load MI projects properly on Windows machines

### ISSUE THREAD

**Issue by ShammiL** [wso2/mi-vscode#126]
**Description:**
After updating the MI VSCode plugin to the latest pre-release version, the MI project explorer and the project overview window does not load the project properly. The issue was noticed only in Windows. 

![image](https://github.com/user-attachments/assets/6174e158-16a6-46ea-932e-6bea41af083c)

This is working fine in previous pre-release versions. 

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by gigara** [comment]
The latest pre-release v0.9.24072507 has resolved the issue. Please reopen if the problem persists.

**Comment by OthmanMoukhli** [comment]
The issue is not fixed
![image](https://github.com/user-attachments/assets/fb22712b-a1f7-49bb-a651-491bfdcc8347)
i can't open any artifact. 
using the latest pre-release version 
![image](https://github.com/user-attachments/assets/dcba9d3b-8454-4d61-939d-0cee99aec22b)

**Comment by gigara** [comment]
@OthmanMoukhli Can you please attach the output channel details?
You can get the output window by `ctrl + shift + u`. In the dropdown select `Micro Integrator`.

**Comment by ShammiL** [comment]
This is fixed in the new pre-release v0.9.24072507
