### ISSUE TITLE
Available data mappers are not displayed under existing mappings.

### ISSUE THREAD

**Issue by chathuranga-jayanath-99** [wso2/mi-vscode#127]
**Description:**
After creating a data mapper, it should appear as an existing mapping when another data mapper is added. However, the existing mappings drop-down list will be empty as shown below.
<img width="437" alt="no-existing-mapping" src="https://github.com/user-attachments/assets/0206163b-af9f-4eb6-9cc3-92b2869433c7">

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
v0.9.24071813

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
1. Create a project. 
2. Add a resource. 
3. Add a new data mapper.
4. Try to add another data mapper and check for previous one. 

**Related Issues:**

**Comment by arunans23** [comment]
This is fixed in the v1.0.0 release.
