### ISSUE TITLE
Improve service parameter visualization in proxy service

### ISSUE THREAD

**Issue by chathuranga-jayanath-99** [wso2/mi-vscode#129]
**Description:**
When adding service parameters to a proxy service, a lengthy parameter name causes the parameter name and value to overlap, as shown below.
<img width="777" alt="proxy-parameter-overlap" src="https://github.com/user-attachments/assets/694866fc-705c-49fe-9705-50a4a58bc348">

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by ChinthakaJ98** [comment]
Closing this issue as it cannot be reproduced in the latest v1.1.0 release. Please reopen if the problem persists.

<img width="706" alt="Screenshot 2024-09-09 at 15 19 28" src="https://github.com/user-attachments/assets/c53a8534-389a-4b98-9f98-9c7041012eb3">
<img width="673" alt="Screenshot 2024-09-09 at 15 19 35" src="https://github.com/user-attachments/assets/9ac3d639-7086-415e-b06a-80141e9f6a1b">
