### ISSUE TITLE
Update form fields for adding new service parameters to display placeholders instead of values

### ISSUE THREAD

**Issue by chathuranga-jayanath-99** [wso2/mi-vscode#130]
**Description:**
$subject

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
v0.9.24071813

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
1. Create a project.
2. Add a proxy service.
3. Go to edit the proxy service.
4. Try to add a new service parameter. 

**Related Issues:**

**Comment by ChinthakaJ98** [comment]
The latest release v1.1.1 has resolved this issue. Please reopen if the problem persists.
