### ISSUE TITLE
Migration from Integration Studio to VSC MI extension

### ISSUE THREAD

**Issue by OthmanMoukhli** [wso2/mi-vscode#133]
**Description:**
Different Issues when migrating a project from Integration Studio with the VSC extension:
- Some Versions don't migrate data sources and data services from integration studio to the extension 
- Some Versions (e.g.[v0.9.24062409](https://github.com/wso2/mi-vscode/releases/tag/v0.9.24062409)) don't display data sources and data services that were migrated even though the files exist 
- Some Versions (e.g. [v0.9.24071508](https://github.com/wso2/mi-vscode/releases/tag/v0.9.24071508)) migrate and display the data source and data service correctly but don't migrate Sequences
- Some Versions (e.g.[v0.9.24062409](https://github.com/wso2/mi-vscode/releases/tag/v0.9.24062409)) don't offer the ability to create a data source or data service 

**Suggested Labels:**
inconsistency

**Suggested Assignees:**

**Affected Product Version:**
[v0.9.24071508](https://github.com/wso2/mi-vscode/releases/tag/v0.9.24071508)
[v0.9.24062409](https://github.com/wso2/mi-vscode/releases/tag/v0.9.24062409)
Other versions as well

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
>migrate a project that has a data source and data service artifact from integration studio to vsc 

**Related Issues:**

**Comment by ChinthakaJ98** [comment]
Closing this issue as the aforementioned behaviours cannot be observed in the latest v1.1.0 release. Please reopen if the problem persists.
