### ISSUE TITLE
Pre-defined list of message stores not available

### ISSUE THREAD

**Issue by DinithiDiaz** [wso2/mi-vscode#134]
**Description:**
Noticed the $subject compared to the [Integration Studio experience](https://mi.docs.wso2.com/en/4.2.0/develop/creating-artifacts/creating-a-message-store/).

In the Store Message form, there is no option to select a previously created message store as a dropdown. Instead, we can only add the created message store by manually entering the name.

   <img width="50%" alt="store-message" src="https://github.com/user-attachments/assets/f2836efe-8bd3-4197-b4e1-517d6b387077">

This is available in Integration Studio as a dropdown under **Available Message Stores**.

![message-store-properties](https://github.com/user-attachments/assets/53059918-6cd0-4b05-874b-cd0021468cb4)

**MI for VS Code Version:** v0.9.24071803 (pre-release)

**Steps to reproduce:**

1. Create a message store.
2. Create an integration sequence.
3. Add Store Message mediator from the Palette.
4. Select a previously created message store.

**Doc Issue:** https://github.com/wso2/docs-mi/issues/534

**Comment by thuva9872** [comment]
The latest pre-release v0.9.24072507 has resolved the issue. Please reopen if the problem persists.
