### ISSUE TITLE
Invalid property scope in property mediator.

### ISSUE THREAD

**Issue by chathuranga-jayanath-99** [wso2/mi-vscode#136]
**Description:**
The available `AXIS2_CLIENT` property scope option adds incorrect value `axis2_client` instead of `axis2-client`.
<img width="444" alt="invalid-property-scope" src="https://github.com/user-attachments/assets/a9c12672-c116-4347-9a9c-c7d83fa7a7ca">

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
v0.9.24071813

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by thuva9872** [comment]
The latest pre-release v0.9.24072507 has resolved the issue. Please reopen if the problem persists.
