### ISSUE TITLE
VSCode Editor diagram breaks if we give sequence in the "on complete" section of aggregate mediator

### ISSUE THREAD

**Issue by uthaiyashankar** [wso2/mi-vscode#137]
- Create a sequence
- Give that sequence in the aggregate mediator -> on complete section
- Getting the attached screenshot
![Screenshot 2024-07-23 at 10 58 23](https://github.com/user-attachments/assets/e004ebd1-7a2c-4055-889f-61910210aa68)

**Comment by gigara** [comment]
The latest pre-release v0.9.24072507 has resolved the issue. Please reopen if the problem persists.
