### ISSUE TITLE
Issue in the diagram alignment with Clone mediator

### ISSUE THREAD

**Issue by tharindulak** [wso2/mi-vscode#146]
**Description:**
Issue in the diagram alignment with Clone mediator

<img width="456" alt="Clone" src="https://github.com/user-attachments/assets/f582bc42-f4af-4092-80ae-91f27e6d9fd5">

Source
```
<?xml version="1.0" encoding="UTF-8"?>
<api context="/arithmaticAPI" name="ArithmaticOperationServiceAPI"
	xmlns="http://ws.apache.org/ns/synapse">
	<resource methods="GET" uri-template="/">
		<inSequence>
			<clone continueParent="true" id="CloneID" sequential="true">
				<target soapAction="Action" to="Address">
					<sequence></sequence>
				</target>
			</clone>
		</inSequence>
		<faultSequence>
		</faultSequence>
	</resource>
</api>
```

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by gigara** [comment]
The latest release v1.1.0 has resolved the issue. Please reopen if the problem persists.
