### ISSUE TITLE
Adding a Fault mediator with SOAP11 generates the synapse config with invalid type for the attribute 'response'

### ISSUE THREAD

**Issue by gabilang** [wso2/mi-vscode#147]
**Description:**

$title
The value of the attribute `response` should be a boolean.

![Screenshot 2024-07-24 at 13 55 13](https://github.com/user-attachments/assets/03a20379-60d6-4a6b-8462-13393eeb7719)

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by thuva9872** [comment]
The latest pre-release v1.0.1 has resolved the issue. Please reopen if the problem persists.
