### ISSUE TITLE
mi-vscode detects as compilation errors when 'onCacheHit' and 'implementation' elements are not defined in Cache mediator configurations. 

### ISSUE THREAD

**Issue by gabilang** [wso2/mi-vscode#148]
**Description:**

$title
But adding those elements with no attributes didn't show any compilation level diagnostics. So defining those can be made as optional. 

![Screenshot 2024-07-24 at 15 19 42](https://github.com/user-attachments/assets/fc37a576-e13f-4b13-ac3b-72bff8ac7af4)

 
**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by thuva9872** [comment]
The latest pre-release v1.0.1 has resolved the issue. Please reopen if the problem persists.
