### ISSUE TITLE
Adding a property mediator with the scope AXIS2_CLIENT gives 'org.apache.synapse.SynapseException'

### ISSUE THREAD

**Issue by gabilang** [wso2/mi-vscode#150]
**Description:**

It generates the synapse configs with `axis2_client` as the scope attribute. But it should be `axis2-client`. 

![Screenshot 2024-07-24 at 17 27 55](https://github.com/user-attachments/assets/49975315-d60b-40d4-b95c-014531569310)

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by thuva9872** [comment]
Follow this on: https://github.com/wso2/mi-vscode/issues/136
