### ISSUE TITLE
'serviceURL' attribute of Callout mediator cannot be added through the 'Callout' form

### ISSUE THREAD

**Issue by gabilang** [wso2/mi-vscode#151]
**Description:**

The form to add  the Callout mediator does not have a field for `serviceURL` attribute. 

![Screenshot 2024-07-24 at 17 41 05](https://github.com/user-attachments/assets/b87e4f61-9cf3-435e-98c0-89058e00e8c4)

After manually add this attribute to the Xml synapse, the `serviceURL` field appears in the edit view of the Callout mediator. 

![Screenshot 2024-07-24 at 17 49 40](https://github.com/user-attachments/assets/8e5974b6-7572-4891-8034-120a4d670350)

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by thuva9872** [comment]
Please select "Endpoint Type" as "URL" so that you can enter the "Service URL".

**Comment by gabilang** [comment]
Closing this since it's not a bug.
