### ISSUE TITLE
Property mediator with property data type OM does not accepts values as expression

### ISSUE THREAD

**Issue by gabilang** [wso2/mi-vscode#152]
**Description:**

In the `Edit Property` view, `OM` value cannot be entered as the expression 

![Screenshot 2024-07-24 at 18 05 48](https://github.com/user-attachments/assets/82087cd7-b99a-4d8f-803a-3bcdc8b10834)

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by thuva9872** [comment]
The latest release v1.0.2 has resolved the issue. Please reopen if the problem persists.
