### ISSUE TITLE
Redirection issue in the MI VS Code

### ISSUE THREAD

**Issue by ChinthakaJ98** [wso2/mi-vscode#155]
When we open the source view from the VS Code plugin, multiple redirection issues occur. Herewith a couple of screen recordings are attached for reference.

https://github.com/user-attachments/assets/057716dd-f06e-48d0-ac7b-31442f3f5ef7

https://github.com/user-attachments/assets/027ca767-51b4-4c62-8495-2e01bdf05741

**Comment by gigara** [comment]
The latest pre-release v0.9.24072507 has resolved the issue. Please reopen if the problem persists.

**Comment by KalinduGandara** [comment]
https://github.com/user-attachments/assets/5c53de23-935b-45c4-aa12-287468a58ca0
