### ISSUE TITLE
Invalid XPath error when adding XSLT mediator

### ISSUE THREAD

**Issue by chathuranga-jayanath-99** [wso2/mi-vscode#157]
**Description:**
When adding an XSLT mediator to a sequence. If we provide only the XSLT Schema key only without specifying a Source XPath as below(Note: expression mark is clicked and it can’t be un clicked). 
![xslt-issue](https://github.com/user-attachments/assets/6ed68d18-0819-4478-a73e-9d5e7ac55a83)
It will add and xml element as mentioned below. 

```xml
<xslt key="conf:FIX_XSLT.xslt" source="">
</xslt>
```

If we try to run the project. then it will give the below error. 

`ERROR {XSLTMediatorFactory} - Invalid XPath specified for the source attribute` 

If you remove the `source=""` attribute from the XSLT mediator configuration, it runs fine.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
v0.9.24071803 

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by thuva9872** [comment]
The latest pre-release v1.0.1 has resolved the issue. Please reopen if the problem persists.
