### ISSUE TITLE
Allows to create APIs with same Context

### ISSUE THREAD

**Issue by KCSAbeywickrama** [wso2/mi-vscode#158]
**Description:**
When attempting to create an API with the same Context, it is allowed but fails at runtime due to multiple APIs with the same context.

**Suggested Labels:**
Type/Improvement

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

1. Create 2 APIs
2. Set `/` as the Context in both of them

**Related Issues:**

**Comment by kaumini** [comment]
The latest release v1.1.1 has resolved the issue. Please reopen if the problem persists.
