### ISSUE TITLE
Code property is not updated properly when adding 'Fault' mediator using the form

### ISSUE THREAD

**Issue by gabilang** [wso2/mi-vscode#160]
**Description:**

$title
When setting SOAP version `soap12`, the value attribute of `code` element is not updated with the selected code. 

![Screenshot 2024-07-25 at 15 22 22](https://github.com/user-attachments/assets/09784271-da29-4f94-a0d1-074981038fde)
Here the `Receiver` part is missing in the Xml synapse script. 

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by gabilang** [comment]
It seems the generated name space for soap12 also incorrect. It should be `http://www.w3.org/2003/05/soap-envelope`. Please check on that as well.

**Comment by thuva9872** [comment]
The latest pre-release v1.0.1 has resolved the issue. Please reopen if the problem persists.
