### ISSUE TITLE
Naming inconsistency in PayloadFactory mediator

### ISSUE THREAD

**Issue by chathuranga-jayanath-99** [wso2/mi-vscode#163]
**Description:**
When adding a PayloadFactory mediator, in the mediators list it is indicated `Payload`. But after it get adds to the design pane it is indicated as `PayloadFactory` as indicated below. 
<img width="1032" alt="Screenshot 2024-07-25 at 15 29 30" src="https://github.com/user-attachments/assets/00c9bb87-7778-4362-bb1a-beffbbd08a6d">

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
v0.9.24072507

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by thuva9872** [comment]
The latest release v1.0.5 has resolved the issue. Please reopen if the problem persists.
