### ISSUE TITLE
resource created when creating an API has "/resource" as the uri-template

### ISSUE THREAD

**Issue by ShammiL** [wso2/mi-vscode#164]
**Description:**
When we create an API through the VSCode plugin, the default resource that is created with the API has a `/resource` uri-template.
```
<resource methods="POST" uri-template="/resource">
    <inSequence>
    </inSequence>
    <faultSequence>
    </faultSequence>
</resource>
```

This can be improved for the uri-template to be either `/` or not contain a uri-template for the default resource at all.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by thuva9872** [comment]
The latest pre-release v1.1.0 has resolved the issue. Please reopen if the problem persists.
