### ISSUE TITLE
No option to resize DSS output mapping text box

### ISSUE THREAD

**Issue by SanojPunchihewa** [wso2/mi-vscode#165]
**Description:**
No option to resize DSS output mapping text box. Since there is plenty of space in the side bar, it's better to give an resize option, or automatically stretch to show the complete mapping.

<img width="476" alt="Screenshot 2024-07-25 at 15 53 59" src="https://github.com/user-attachments/assets/405f7a3d-ccdf-445e-a809-34e00f87ecea">

**Comment by ChinthakaJ98** [comment]
The latest release v1.1.1 has resolved this issue. Please reopen if the problem persists.
