### ISSUE TITLE
DSS Output mapping text box adds whitespaces before the text 

### ISSUE THREAD

**Issue by SanojPunchihewa** [wso2/mi-vscode#166]
**Description:**
DSS Output mapping text box adds whitespaces before the text 

<img width="435" alt="Screenshot 2024-07-25 at 16 00 07" src="https://github.com/user-attachments/assets/7c9d2ca1-20aa-48ff-baa6-56f4e3bbae65">

**Comment by ChinthakaJ98** [comment]
The latest release v1.1.1 has resolved this issue. Please reopen if the problem persists.
