### ISSUE TITLE
Hello World Service Sample contains the deprecated <outSequence/>

### ISSUE THREAD

**Issue by DinithiDiaz** [wso2/mi-vscode#168]
**Description:**
$subject

<img width="1108" alt="hello world" src="https://github.com/user-attachments/assets/8d61839f-a6c3-4015-8be8-42bbc32dd589">

---

**Affected Product Version:** v0.9.24072507 (pre-release)

**Comment by ChinthakaJ98** [comment]
This issue has been resolved as the hosted sample files have been updated.

<img width="1134" alt="Screenshot 2024-09-13 at 11 54 47" src="https://github.com/user-attachments/assets/dae55a1a-8a76-4038-bdd0-96368998a99d">
