### ISSUE TITLE
Property (any first) mediator haven't been added to API resource view

### ISSUE THREAD

**Issue by malakaganga** [wso2/mi-vscode#172]
**Steps to reproduce:**

When API is created and resource is added then when we add property mediator (any mediator) as the first mediator we can't see it in the resource UI but in XML it's there.

After reloading it was successful and couldn't reproduce again.

**OS, DB, other environment details and versions:**    

Java version: 17.0.11
Ubuntu 22.04

**Comment by thuva9872** [comment]
Closing this issue as it cannot be reproduced. Please feel free to reopen it if you have any further concerns.
