### ISSUE TITLE
Incorrect code generated for the Aggregate mediator when no value provided for the `Completion Timeout` field in completeCondition

### ISSUE THREAD

**Issue by poorna2152** [wso2/mi-vscode#173]
**Description:**
When the value of the `Completion Timeout` field is removed when creating an aggregate mediator the code generated is invalid and looks like the code below.

```xml
<aggregate id="ScatterGatherProxy">
  <completeCondition timeout="">
	  <messageCount max="-1" min="-1" />
  </completeCondition>
  <onComplete aggregateElementType="root"
	  expression="&#x2F;&#x2F;*[local-name() &#x3D; &#39;MissionResult&#39;]"></onComplete>
  </aggregate>
```
<img width="452" alt="Screenshot 2024-07-25 at 16 53 18" src="https://github.com/user-attachments/assets/ac2bff64-5ca3-4e13-ac90-334ef424243a">
 below.

**Comment by thuva9872** [comment]
The latest pre-release v1.0.1 has resolved the issue. Please reopen if the problem persists.
