### ISSUE TITLE
Change Input Schema window not opened in the Data Mapper for CSV

### ISSUE THREAD

**Issue by SanojPunchihewa** [wso2/mi-vscode#175]
**Description:**

When we double click the existing schema, Change Output Schema window is opened. However the change Input schema is not opened when we double click the Input schema.

<img width="1657" alt="Screenshot 2024-07-25 at 16 58 27" src="https://github.com/user-attachments/assets/f3ca96c8-79fb-407f-a470-83c6e2b50a46">

**Comment by arunans23** [comment]
Fixed in 1.1.0.
