### ISSUE TITLE
Input Schema is not populated in the Data Mapper for CSV payload

### ISSUE THREAD

**Issue by SanojPunchihewa** [wso2/mi-vscode#177]
**Description:**

Try to use the following CSV data as the input for the data mapper. The input mapping is not shown, however the same CSV works well in the Integration Studio.

```csv
firstname,surname,phone,state
First,User,061787878,34
ABC,User,0617998989,22
DEF,User,076144123,54
```

<img width="617" alt="Screenshot 2024-07-25 at 17 11 17" src="https://github.com/user-attachments/assets/11d6db18-fd5d-4a09-acac-2218055d4de2">

**Comment by SanojPunchihewa** [comment]
This seems to be an UX issue was solved after a call with @arunans23. Better if we could improve the UI/UX

**Comment by arunans23** [comment]
Here, we need to map the arrays from Input to Output and then drill down further to view the underlying elements inside the array.


https://github.com/user-attachments/assets/0333bd2d-94dc-45f9-9bad-59f2b941584f
