### ISSUE TITLE
Cannot define a message store as an XPath expression using the diagram view 

### ISSUE THREAD

**Issue by gabilang** [wso2/mi-vscode#179]
**Description:**

Providing the following config to define a message store using XPath expression results in corrupted value for `messageStore` attribute. 
```xml
<inSequence>
    <store messageStore="{//ser:getQuote/ser:request/ser:symbol}" xmlns:ser="http://services.samples"/>
</inSequence>
```

![Screenshot 2024-07-25 at 17 17 46](https://github.com/user-attachments/assets/45969c7e-1c4a-447a-959c-528ef0252dfa)

Then open the source view and edit view appears as 

![Screenshot 2024-07-25 at 17 08 51](https://github.com/user-attachments/assets/ff81dc7d-39d8-4f99-9039-4ccd0ffe9eb9)

Not sure on that we can still directly use an `XPath` expression within the `messageStore` attribute of the `<store>` mediator. 

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by thuva9872** [comment]
Follow this on: https://github.com/wso2/mi-vscode/issues/37
