### ISSUE TITLE
Running a project through the VSCode plugin will remove all capps deployed

### ISSUE THREAD

**Issue by ShammiL** [wso2/mi-vscode#18]
**Description:**
When a project is run from the VSCode plugin, it will clear all capps currently residing in the `carbonapps` directory. This would mean a user can't have multiple capps deployed at a time and any capps that were deployed earlier will be lost.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by ShammiL** [comment]
Any content that was in the `MI_HOME/lib` directory are also removed when run from the VSCode.

**Comment by ShammiL** [comment]
Noticed the same happening when just building the CAPP using the Build button in the MI Overview page

**Comment by gigara** [comment]
The latest pre-release v0.9.24072507 has resolved the issue. Please reopen if the problem persists.
