### ISSUE TITLE
When an `id` is not provided for aggregate mediator the code generated shows and empty string as the id

### ISSUE THREAD

**Issue by poorna2152** [wso2/mi-vscode#180]
**Description:**
The aggregate id is an [optional field](https://mi.docs.wso2.com/en/latest/reference/mediators/aggregate-mediator/) in the aggregate mediator and when an aggregate id is not provided in the vscode form the generated code contains an empty string as the aggregate id.

**Comment by thuva9872** [comment]
This is already fixed in the v1.0.0
