### ISSUE TITLE
When value field of the property mediator has `"` characters the generated code contains an error

### ISSUE THREAD

**Issue by poorna2152** [wso2/mi-vscode#181]
**Description:**
Consider the following values for the property mediator form,
<img width="516" alt="Screenshot 2024-07-25 at 17 54 47" src="https://github.com/user-attachments/assets/05df5230-0c37-434c-9d46-61073c0dc8f1">
When the value field contains `"` the code generated code gives an error.

**Comment by thuva9872** [comment]
This is already fixed.
