### ISSUE TITLE
Task message is encoded

### ISSUE THREAD

**Issue by SanojPunchihewa** [wso2/mi-vscode#182]
**Description:**

Schedule tasks won't work as the message element is encoded. We should have it as follows without encoding,

```
<message @_xmlns=""></message>
```

**Comment by thuva9872** [comment]
@SanojPunchihewa could you please try with the latest version 1.0.1?

**Comment by SanojPunchihewa** [comment]
This seems to be fixed in latest version

**Comment by thuva9872** [comment]
Closing this as it is already fixed. Please reopen if you have any more concerns.
