### ISSUE TITLE
When the `action` is `set` for the property mediator the form allows creating property mediator with an empty value  

### ISSUE THREAD

**Issue by poorna2152** [wso2/mi-vscode#183]
**Description:**
It should not be allowed to create a property mediator with the `Property Action` set to `set` and the `Property Value` set to empty. The Property mediator allows this and this as results generates an error when running the code.

**Comment by thuva9872** [comment]
Unable to reproduce this. Could you please provide the steps to reproduce?

**Comment by thuva9872** [comment]
This is already fixed.
