### ISSUE TITLE
The creation form for Inbound endpoint has changed in the recent pre-release(v0.9.24072507)

### ISSUE THREAD

**Issue by ShammiL** [wso2/mi-vscode#184]
**Description:**
The recent pre-release v0.9.24072507 of the VSCode plugin shows the below form when trying to create an inbound endpoint.
![image](https://github.com/user-attachments/assets/ae075881-c86f-46c6-8f4e-17b68988509d)

This does not offer any of the options that are needed to create an inbound EP.

Below is the form that was displayed until the previous pre-release, attached for reference.
![image](https://github.com/user-attachments/assets/a2dc3a43-c278-461b-b38d-f0638ad37c20)

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by poorna2152** [comment]
When clicking on a one here this redirects to a page with "Downloading Connector" message and stays stuck in there

**Comment by thuva9872** [comment]
The latest release v1.0.1 has resolved the issue. Please reopen if the problem persists.
