### ISSUE TITLE
When we create a complex integration with multiple branches the diagram goes out of the working view

### ISSUE THREAD

**Issue by malakaganga** [wso2/mi-vscode#188]
**Description:**
When we create a complex integration with multiple branches the diagram goes out of the working view.

For example create the below API 

https://github.com/wso2/mule-conversion-samples/blob/master/examples/filtering-a-message/FilteringAMessage/src/main/synapse-config/api/FilteringAMessage.xml

when adding the last filter the focus view becomes blank we have to drag to the right to see the diagram

**Comment by gigara** [comment]
The latest release v1.1.1 has resolved the issue. Please reopen if the problem persists.
