### ISSUE TITLE
VS code command palette MI command not working

### ISSUE THREAD

**Issue by KalinduGandara** [wso2/mi-vscode#189]
**Description:**
When run command pallete MI commands give error
`Cannot read properties of undefined (reading 'info')`

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by gigara** [comment]
@KalinduGandara Please provide more information.
1. Which command/s are failing?
2. What is the OS, version?
3. What is the extension version?
4. In which state you are executing the command?

**Comment by KalinduGandara** [comment]
1. MI: Add API, MI: Add Endpoint, MI: Add Sequence and other MI: Add commands
2. macOS ventura 13.0.1
3. v0.9.24072507 
4. After creating new MI project

**Comment by hevayo** [comment]
We will hide these commands from the palate. Need to find a proper fix by obtaining project path. Also these commands should only available if project is a new MI project.

**Comment by ChinthakaJ98** [comment]
Closing this issue as the aforementioned commands have been hidden from the palate in the latest v1.1.0 release. Please reopen if the problem persists.
