### ISSUE TITLE
New endpoint cannot be added to a call mediator through the UI after deleting it

### ISSUE THREAD

**Issue by ShammiL** [wso2/mi-vscode#190]
**Description:**
We can delete an endpoint in a call mediator but once it is deleted there is no way to add a new endpoint again through the UI
![image](https://github.com/user-attachments/assets/f83ab593-b898-4fc1-934e-c7478a2b232e)

![image](https://github.com/user-attachments/assets/8e5b6d56-da07-4045-9e36-ec1416878fbd)

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by thuva9872** [comment]
This issue could not be reproduced in the latest version (v1.1.0). Hence closing this issue. Please reopen if you have any concerns.
