### ISSUE TITLE
More strict validation in API version input

### ISSUE THREAD

**Issue by GDLMadushanka** [wso2/mi-vscode#192]
**Description:**
Even though version "v1" in the following config is valid. I'm getting invalid version format error
`<api context="/api" name="CustomerProfile" version="v1" version-type="context" xmlns="http://ws.apache.org/ns/synapse">`

<img width="703" alt="Screenshot 2024-07-25 at 19 11 44" src="https://github.com/user-attachments/assets/3709ff2c-130c-48d4-bc17-edd381ae8cd4">

**Affected Product Version:**
v0.9.24072507

**Comment by thuva9872** [comment]
The latest pre-release v1.1.0 has resolved the issue. Please reopen if the problem persists.
