### ISSUE TITLE
Adding a large expression in payload factory arguments breaks the view

### ISSUE THREAD

**Issue by GDLMadushanka** [wso2/mi-vscode#198]
**Description:**
When we add a long expression in payload factory it renders over other elements and breaks the view

<img width="392" alt="Screenshot 2024-07-25 at 19 41 53" src="https://github.com/user-attachments/assets/817a69c3-5710-40fb-98e3-17f9e2c222fb">

**Affected Product Version:**
v0.9.24072507

**Steps to reproduce:**
Expression : `(fn:round(1.17 * get-property('query.param.amount') div get-property('query.param.term') * 100) div 100)`

**Comment by gigara** [comment]
The latest release v1.1.0 has resolved the issue. Please reopen if the problem persists.
