### ISSUE TITLE
After deleting API, it does not allow to add an API with same name

### ISSUE THREAD

**Issue by chanikag** [wso2/mi-vscode#199]
**Description:**
Steps to reproduce:
1. Create an API
2. Delete the default resource
3. Delete the API
4. Try to add a new API with the same name, but it does not allow

<img width="1660" alt="Screenshot 2024-07-25 at 7 56 40 PM" src="https://github.com/user-attachments/assets/53ef51ca-f290-40f6-a8b4-212c97d7bafe">

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by gigara** [comment]
@chanikag Can you please try this with the latest extension version (v1.0.0)?

**Comment by ChinthakaJ98** [comment]
This issue can be reproduced in the latest release as well.


https://github.com/user-attachments/assets/41486be6-6dbf-4fd1-b584-e774f447c0cb

**Comment by gigara** [comment]
The latest release v1.1.1 has resolved the issue. Please reopen if the problem persists.
