### ISSUE TITLE
How I can download the extension

### ISSUE THREAD

**Issue by AboOmar** [wso2/mi-vscode#2]
**Description:**

There is no extension with the name "Micro Integrator for VSCode" in VSCode marketplace, also there is no vsix file that can be downloaded and installed in VSCode.

**Comment by DinithiDiaz** [comment]
Hi @AboOmar, 

The **Micro Integrator** extension can be installed from [here](https://marketplace.visualstudio.com/items?itemName=WSO2.micro-integrator).

Follow the [Micro Integrator documentation](https://mi.docs.wso2.com/en/latest/develop/mi-for-vscode/install-wso2-mi-for-vscode/) for more details on installation.

Thanks & Kind Regards,
Dinithi
