### ISSUE TITLE
Expression editor is not shown HTTP Endpoint Auth configs

### ISSUE THREAD

**Issue by SanojPunchihewa** [wso2/mi-vscode#200]
**Description:**

HTTP endpoint Auth configs (Basic and OAuth) has expression support for all the parameters. But in VSCode, the expression enable button is not shown.

<img width="675" alt="Screenshot 2024-07-25 at 20 04 50" src="https://github.com/user-attachments/assets/88b37e41-b532-431d-abdb-992a83142950">

**Comment by ChinthakaJ98** [comment]
Hi @SanojPunchihewa,

We can add the expression in the textfield itself if required with curly brackets right? The reason not to use the expression editor here was because in these cases we do not need to add any namespaces and therefore just the textfield was sufficient.

**Comment by SanojPunchihewa** [comment]
Yes it works with curly brackets. Since we show `EX` in other places where we allow expression, a new user may be uncertain. We may need to update the document accordingly.

**Comment by ChinthakaJ98** [comment]
Agreed. We will give the option to add an expression here as well to make it more clear to a new user.

**Comment by SanojPunchihewa** [comment]
I tested this and it seems to work smoothly. Thanks for the effort
