### ISSUE TITLE
VSCode does not validate retry error codes provided when creating an endpoint

### ISSUE THREAD

**Issue by ShammiL** [wso2/mi-vscode#204]
**Description:**
At the moment we can provide any value as retry error codes and suspend error codes in the Endpoint error handling section when creating and endpoint. This can be improved to validate if only numeric values separated by commas are provided. 

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by ChinthakaJ98** [comment]
The latest release v1.1.1 has resolved this issue. Please reopen if the problem persists.
