### ISSUE TITLE
The property "Initialize Axis2 Client Options" in the Call Mediator cannot be modified.

### ISSUE THREAD

**Issue by chathuranga-jayanath-99** [wso2/mi-vscode#208]
**Description:**
When adding a Call Mediator, we can select the property `Initialize Axis2 Client Options` under the "Advanced" section. However, even if we create a Call Mediator without selecting this property initially, it will add the Call Mediator with this property selected.
Additionally, when adding a Call Mediator with the `Initialize Axis2 Client Options` property selected, it adds an element similar to the one below to the source code, but there is no indication of this selected property.
```xml
<call>
    <endpoint key="NumberAdditionEP"/>
</call>
```

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
v0.9.24072507

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
1. Create an address endpoint. 

Scenario 1
1. Add a call mediator without selecting the property `Initialize Axis2 Client Options`.
2. Try to edit the call mediator and check the status of the property `Initialize Axis2 Client Options`.

Scenario 2
1. Add a call mediator selecting the property `Initialize Axis2 Client Options`.
2. View the source of the added call mediator.

**Related Issues:**

**Comment by thuva9872** [comment]
`initAxis2ClientOptions` attribute will be only added if the `Enable Blocking Calls` is true and `Initialize Axis2 Client Options` is false.

**Comment by thuva9872** [comment]
By default the value is true in the runtime. So we don't need to define it in the xml.

**Comment by thuva9872** [comment]
The latest pre-release v1.0.1 has resolved the issue. Please reopen if the problem persists.
