### ISSUE TITLE
Database connection gives an error when the parameters are added to the source code and not provided in the expected order

### ISSUE THREAD

**Issue by poorna2152** [wso2/mi-vscode#21]
**Description:**
When the following code is pasted to the source an error is thrown, saying `Element name 'user' is invalid.`
```
 <connection>
   <pool>
     <password>db-password</password>
     <user>db-username</user>
     <url>jdbc:mysql://localhost:3306/test</url>
     <driver>com.mysql.jdbc.Driver</driver>
   </pool>
</connection>
```
However when the order of the parameters in the `<pool>` is changed this error is not there anymore.
```
<connection>
  <pool>
	<driver>com.mysql.jdbc.Driver</driver>
	<url>jdbc:mysql://localhost:3306/test</url>
	<user>db-username</user>
	<password>db-password</password>
  </pool>
</connection>
```

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by thuva9872** [comment]
Hi,

To ensure compliance with the XML schema, where element order is enforced, it's crucial to use forms for creating mediators instead of copying them. This approach guarantees that elements are entered in the required sequence, thus solving the problem effectively.

Thanks,
Thuvarakan
