### ISSUE TITLE
Error sequence not created when creating an Inbound Endpoint

### ISSUE THREAD

**Issue by SanojPunchihewa** [wso2/mi-vscode#211]
**Description:**

When creating an Inbound endpoint, we need to specify the injecting sequence and error sequence. When an inbound is created, the VSCode plugin will create an empty sequence with the given name for injecting sequence. But a sequence with the error sequence identifier is not created.

Plugin version : v1.0.0 (pre-release)

**Comment by kaumini** [comment]
The latest release v1.0.1 has resolved the issue. Please reopen if the problem persists.
