### ISSUE TITLE
"name" element is added twice in the localEntry when creating a file connection

### ISSUE THREAD

**Issue by sajinieKavindya** [wso2/mi-vscode#216]
**Description:**

After a file connection is configured in the form view, two "name" elements are added to the corresponding localEntry configuration.

<img width="689" alt="Screenshot 2024-07-26 at 08 27 54" src="https://github.com/user-attachments/assets/590d9c17-a806-44a3-aa38-1c137ca809e2">

**Comment by kaumini** [comment]
The latest release v1.0.1 has resolved the issue. Please reopen if the problem persists.
