### ISSUE TITLE
Invalid value "true" is selected in the dropdown box for the fileLockScheme property in the file connection creation view for Local connection type

### ISSUE THREAD

**Issue by sajinieKavindya** [wso2/mi-vscode#217]
**Description:**

The valid values for the File Locking Behaviour (fileLockScheme) parameter for **Local connection type** are `Local` and `Cluster`. But in the file connection creation view, the value is set to `true` in the dropdown list by default. However, in the source view, the value is saved as `Local`.

<img width="684" alt="Screenshot 2024-07-26 at 08 49 17" src="https://github.com/user-attachments/assets/572ef5d9-65a5-4102-b261-35782a932100">

**Comment by gigara** [comment]
The latest release v1.1.0 has resolved the issue. Please reopen if the problem persists.
