### ISSUE TITLE
HTTP and HTTPS Form View has "Port" parameter twice

### ISSUE THREAD

**Issue by SanojPunchihewa** [wso2/mi-vscode#218]
**Description:**

It seems we have used the same Display Name for `inbound.http.port` and `inbound.worker.pool.size.max` parameters.

<img width="671" alt="Screenshot 2024-07-26 at 09 24 33" src="https://github.com/user-attachments/assets/37e505bf-3dc7-4f97-80cd-7ad125016e5f">

**Comment by kaumini** [comment]
The latest release v1.0.1 has resolved the issue. Please reopen if the problem persists.
