### ISSUE TITLE
Not possible to add new registry through the `Registry Explorer`

### ISSUE THREAD

**Issue by poorna2152** [wso2/mi-vscode#221]
**Description:**
There is no `+` button in the registry explorer to add a new registry artifact.

<img width="410" alt="image" src="https://github.com/user-attachments/assets/761a3542-bf67-4ffd-a70e-ca45579ae6a5">

**Comment by thuva9872** [comment]
The latest release v1.0.2 has resolved the issue. Please reopen if the problem persists.
