### ISSUE TITLE
The property "Serialize Response" in the Fault Mediator cannot be modified.

### ISSUE THREAD

**Issue by chathuranga-jayanath-99** [wso2/mi-vscode#222]
**Description:**
When adding a Fault Mediator, we can select the property `Serialize Response`. However, even if we create a Fault Mediator without selecting this property, it will add the Fault Mediator with this property selected. 

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
v0.9.24072507

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
1. Add a Fault Mediator without selecting the property `Serialize Response`.
2. Try to edit the Fault mediator and check the status of the property `Serialize Response`.

**Related Issues:**

**Comment by thuva9872** [comment]
This is fixed in v1.0.1.
