### ISSUE TITLE
The property "Code" in the Fault Mediator cannot be modified.

### ISSUE THREAD

**Issue by chathuranga-jayanath-99** [wso2/mi-vscode#224]
**Description:**
When adding a Fault mediator, we get to select properties `SOAP Version` and `Code`. Adding a Fault mediator with `soap12` as `SOAP Version` and selecting any from the drop down for `Code` will result in adding a Fault mediator with `Receiver` as `Code`. Also after creating `Code` value can't be modified from `Receiver`. 

When adding a Fault Mediator, we can select the property Serialize Response. However, even if we create a Fault Mediator without selecting this property, it will add the Fault Mediator with this property selected.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
v0.9.24072507

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
1. Add a Fault mediator. 
2. Select `soap12` as `SOAP Version`. 
3. Select `Sender` as `Code`.
4. Finish adding Fault mediator. 
5. Try to edit the Fault mediator and check the value of `Code`. 

Note: Same behavior can be observed for any other value for `Code`. 

**Related Issues:**

**Comment by thuva9872** [comment]
Follow this on: https://github.com/wso2/mi-vscode/issues/160
