### ISSUE TITLE
In the edit view of header mediator the scope attribute changes back to it default value

### ISSUE THREAD

**Issue by gabilang** [wso2/mi-vscode#231]
**Description:**

In the edit view of header mediator the scope attribute changes back to `default` when opening it again after set it's value to `transport`. UI perspective, it can be improved. 

![Screenshot 2024-07-26 at 14 12 44](https://github.com/user-attachments/assets/4aae24f7-2e7f-4b7b-9b50-9e726a5d3aa5)

 

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by thuva9872** [comment]
The latest release v1.0.2 has resolved the issue. Please reopen if the problem persists.
