### ISSUE TITLE
Some operations in data mapper are not available in the set of operations

### ISSUE THREAD

**Issue by poorna2152** [wso2/mi-vscode#233]
**Description:**
Some operations of the data mapper described in the documentation are not available in the VS Code. For example, the `multiply` operation is not there. 
https://mi.docs.wso2.com/en/latest/reference/mediators/data-mapper-mediator/

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by ChinthakaJ98** [comment]
When comparing the data mapper that we have in the Integration Studio with the VS Code MI Extension, a few basic operations have been taken out intentionally as they can now be interpreted arithmetically via the expression editor in the MI extension. The documentation of the latest 4.3.0 version [1] has been updated accordingly by removing such operations. The documentation of the 4.2.0 version [2] can be referred to get an idea about the operations that we have in the Integration Studio.

[1] https://mi.docs.wso2.com/en/latest/reference/mediators/data-mapper-mediator
[2] https://mi.docs.wso2.com/en/4.2.0/reference/mediators/data-mapper-mediator
