### ISSUE TITLE
Error diagnostic not show in the Data Mapper when there is an error in the expression in a mapping

### ISSUE THREAD

**Issue by poorna2152** [wso2/mi-vscode#234]
**Description:**
Consider a json to json mapping and for a field of type string in the input and the output we use the `sum` function.
In the code generated an error is shown with the message, `Argument of type 'string' is not assignable to parameter of type 'number'.ts(2345)`. But in the UI in the data mapping no such error is shown. The error should be shown here because the sum function cannot be used with an string input

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by KCSAbeywickrama** [comment]
@poorna2152 are you referring to a this type of scenario. Seems like errors in the mapping showing correctly. 
![image](https://github.com/user-attachments/assets/7cd690d6-a892-470d-9ea2-357b6a45b91a)

If you are referring to different case please provide exact steps to reproduce

**Comment by poorna2152** [comment]
This is the case that I was referring to. This did not work previously. Seems to be working now. Thus closing the issue
