### ISSUE TITLE
Drop mediator's description field is now mandatory in v1.0.0

### ISSUE THREAD

**Issue by gabilang** [wso2/mi-vscode#237]
**Description:**

$title
It can be made it as optional as earlier. 

<img width="1728" alt="Screenshot 2024-07-26 at 17 15 36" src="https://github.com/user-attachments/assets/72f6216b-d0d6-4da0-96ae-568f3f22da03">

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by thuva9872** [comment]
The latest release v1.0.2 has resolved the issue. Please reopen if the problem persists.
