### ISSUE TITLE
Add support for environment variables thru custom launch.json config

### ISSUE THREAD

**Issue by wx-yz** [wso2/mi-vscode#24]
**Description:**

Add feature to be able to support environment variables from launch.json config. When there are external params that accept environment variables there's no way to add them during Run and Debug config. Typically in other launch types such an NodeJS, you can add the "env" param and add environment variables

![image](https://github.com/wso2/mi-vscode/assets/57770159/a56024d4-1c8c-4f7c-995e-dfd8f26132f1)

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by gigara** [comment]
The latest pre-release v0.9.24072507 has resolved the issue. Please reopen if the problem persists.
