### ISSUE TITLE
Modifying the local entry, originally configured using a `source URL entry`, gets converted to an `inline XML entry`.

### ISSUE THREAD

**Issue by chathuranga-jayanath-99** [wso2/mi-vscode#242]
**Description:**
After creating a local entry using a source URL, modifying its values will change its type to an inline XML entry. Updates will also modify the source XML to reflect an inline XML entry format.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
v1.0.1

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by thuva9872** [comment]
The latest release v1.0.5 has resolved the issue. Please reopen if the problem persists.
