### ISSUE TITLE
New mediator got added in wrong place in nested switch mediator

### ISSUE THREAD

**Issue by thuva9872** [wso2/mi-vscode#247]
**Description:**
When adding a mediator next to the nested switch mediator, it got added in the wrong place.

![image](https://github.com/user-attachments/assets/4b142edb-bdf2-46bc-8809-f220cc4d869e)

When adding a new mediator at `Place A` it got added in `Place 1` instead of `Place 2`

**Steps to reproduce:**
```
<?xml version="1.0" encoding="UTF-8"?>
<api context="/loan" name="Loan" xmlns="http://ws.apache.org/ns/synapse">
	<resource methods="GET" uri-template="/calculate*">
		<inSequence>
			<switch source="def">
				<case regex="case">
					<switch source="abc">
						<case regex="case">
						</case>
						<default></default>
					</switch>
				</case>
				<default></default>
			</switch>
		</inSequence>
		<faultSequence>
		</faultSequence>
	</resource>
</api>
```

Try to add a log mediator at the first switch mediator ( at place A).

**Comment by gigara** [comment]
The latest release v1.1.0 has resolved the issue. Please reopen if the problem persists.
