### ISSUE TITLE
New call endpoint creation form doesn't provide inline endpoint option

### ISSUE THREAD

**Issue by ShammiL** [wso2/mi-vscode#248]
**Description:**
The form to create a new Call endpoint doesn't allow the user to create inline endpoints.
![image](https://github.com/user-attachments/assets/bc28cd04-ac11-4a8f-96a7-318f03cc73e3)

But this option in visible in the Edit call endpoint form when the relevant call mediator already has an inline endpoint.
![image](https://github.com/user-attachments/assets/87450052-5a59-4118-9a73-4006972b621e)

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by thuva9872** [comment]
The latest release v1.0.2 has resolved the issue. Please reopen if the problem persists.
