### ISSUE TITLE
Can't edit a registry resource to add registry properties after creation

### ISSUE THREAD

**Issue by chathuranga-jayanath-99** [wso2/mi-vscode#250]
**Description:**
The functionality to add registry properties after the creation of a registry resource is available in the integration studio. But it is not available in the MI VS Code. 

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
v1.0.1

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
1. Create a registry resource. 
2. Go to `Registry Explorer`.
3. Select the added registry resource and try to edit. 

**Related Issues:**

**Comment by rosensilva** [comment]
Add doc to the doc site once this feature is complete

**Comment by ChinthakaJ98** [comment]
Closing this issue as it cannot be reproduced in the latest v1.1.0 release. Please reopen if the problem persists.

<img width="726" alt="Screenshot 2024-09-23 at 12 33 45" src="https://github.com/user-attachments/assets/f648c2e4-991f-47a2-a4a4-4484490d7652">
