### ISSUE TITLE
The description field in the creation form for Drop mediator is a required field

### ISSUE THREAD

**Issue by ShammiL** [wso2/mi-vscode#252]
**Description:**
The description field in the creation form for the Drop mediator is a required field although it should be optional.
![image](https://github.com/user-attachments/assets/26cfb421-d332-4157-a3a8-55d75233c206)

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by thuva9872** [comment]
Duplicate: https://github.com/wso2/mi-vscode/issues/237
