### ISSUE TITLE
Formatting of fonts can be improved in Endpoint artifacts form

### ISSUE THREAD

**Issue by gabilang** [wso2/mi-vscode#257]
**Description:**

$title
![Screenshot 2024-07-30 at 10 59 43](https://github.com/user-attachments/assets/4da0acce-0e3e-4f9d-a4ae-edffef7c719e)

It looks like there are inconsistencies in font size and style in the form. 

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by ChinthakaJ98** [comment]
Hi @gabilang,

All components used in the aforementioned Address Endpoint form are from the ui-toolkit and they are used throughout the MI extension. Therefore ideally there cannot be any inconsistencies as such. Could you please try again with the latest release and share a screenshot with the areas marked where you could observe any kind of inconsistency?

**Comment by ChinthakaJ98** [comment]
Closing this issue as it cannot be reproduced in the latest v1.1.0 release. Please reopen if the problem persists.
