### ISSUE TITLE
Can't change the message store type after creation

### ISSUE THREAD

**Issue by ShammiL** [wso2/mi-vscode#262]
**Description:**
When we create a message store, the creation form allows the user to change the message store type.
![image](https://github.com/user-attachments/assets/cee326ad-c2c0-4bd3-8051-17e2d1e0529b)

However, the same is not allowed when editing an already-created message store.
![image](https://github.com/user-attachments/assets/787bb0ee-4630-42a5-b57a-7741805f38d5)

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by thuva9872** [comment]
This is the expected behaviour.

**Comment by anupama-pathirage** [comment]
Closing the issue as per the above comment.
