### ISSUE TITLE
Provider URL with tcp not accepted when creating JMS message store

### ISSUE THREAD

**Issue by ShammiL** [wso2/mi-vscode#263]
**Description:**
When we create a JMS message store, providing `tcp://localhost:61616` as the provider URL gives an error "Invalid Provider URL"
![image](https://github.com/user-attachments/assets/51bdbd2c-d85b-4c15-8b1c-0fe8e87321f9)
The error would no longer be visible if `tcp` is changed to something else(e.g. `http`).

But when it comes to JMS message stores, `HTTP` is not a recognized transport schema.
> INFO {JmsStore} - Store [Original]. Initialization failed... javax.jms.JMSException: Could not create Transport. Reason: java.io.IOException: Transport scheme NOT recognized: [HTTP]

The validation logic of the Provider URL field needs to be updated accordingly.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by thuva9872** [comment]
The latest release v1.0.5 has resolved the issue. Please reopen if the problem persists.
