### ISSUE TITLE
Local entries defined with XSLT are not appearing in the schema key dropdown in the XSLT mediator.

### ISSUE THREAD

**Issue by chathuranga-jayanath-99** [wso2/mi-vscode#265]
**Description:**
A defined local entry with XSLT should appear in the dropdown list for the schema key property in the property window when adding an XSLT mediator. However, currently, the appearing dropdown is empty.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
v1.0.1

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by thuva9872** [comment]
The latest release v1.0.5 has resolved the issue. Please reopen if the problem persists.
