### ISSUE TITLE
Creating a local entry with XML resulted in an incorrect XML source for the local entry.

### ISSUE THREAD

**Issue by chathuranga-jayanath-99** [wso2/mi-vscode#267]
**Description:**
Adding a local entry with XML will use the provided XML as input and update the source XML of the local entry with this input.

Consider using the following XML as the input:
```xml
<?xml version="1.0" encoding="UTF-8"?>
    <library>
        <book>
            <title>The Great Gatsby</title>
            <author>F. Scott Fitzgerald</author>
        </book>
    </library>
```
Although the XML is considered valid, the following issues were observed once it was provided:

The source view of the added local entry appears as shown below, which is incorrect.
```xml
<?xml version="1.0" encoding="UTF-8"?>
<localEntry key="books2le" xmlns="http://ws.apache.org/ns/synapse">
    <?xml version="1.0" encoding="UTF-8"?>
    <library>
        <book>
            <title>The Great Gatsby</title>
            <author>F. Scott Fitzgerald</author>
        </book>
    </library>
</localEntry>
```

Additionally, when checking the local entry in the Project Explorer, we will see only a single XML line, as indicated below.
```xml
?xml version="1.0" encoding="UTF-8"?>
```

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
v1.0.1

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
1. Create a local entry with the above mentioned input xml. 
2. Go to the source view of the added local entry and check the source xml. 
3. Select the local entry from the Project Explorer and view the available content. 

**Related Issues:**

**Comment by thuva9872** [comment]
The latest release v1.0.5 has resolved the issue. Please reopen if the problem persists.
