### ISSUE TITLE
Clicking on the already created Task artifact does not open the form view  

### ISSUE THREAD

**Issue by gabilang** [wso2/mi-vscode#269]
**Description:**

$title

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
1. Create a task
2. Close the design view
3. Click on the created Task artifact from the sidebar (MI Project Explorer) 

The 'Task Form' should be opened. 

**Related Issues:**

**Comment by thuva9872** [comment]
Hi @gabilang,

We can open the form view from the `Edit` button in the task view diagram.
<img width="687" alt="image" src="https://github.com/user-attachments/assets/0937a7f5-ed66-4b83-ae0c-1a3ec0c7fdea">

**Comment by anupama-pathirage** [comment]
Closing as per the above comment.
