### ISSUE TITLE
Not possible to define inline endpoints in vscode

### ISSUE THREAD

**Issue by poorna2152** [wso2/mi-vscode#27]
**Description:**
In the call mediator it is not possible to define an inline endpoint, rather an endpoint created separately have to be used.

**Comment by KalinduGandara** [comment]
If an XML with an inline endpoint is opened, it will not display correctly and will cause an error in the resource view.
<img width="1220" alt="Screenshot 2024-07-04 at 13 42 04" src="https://github.com/wso2/mi-vscode/assets/80283061/f9c1f522-3be1-4a11-a9b1-91d5b8611bd8">

**Comment by gigara** [comment]
The latest pre-release v0.9.24072507 has resolved the issue. Please reopen if the problem persists.
