### ISSUE TITLE
Properties of custom tasks cannot be set via the design view

### ISSUE THREAD

**Issue by gabilang** [wso2/mi-vscode#271]
**Description:**

This feature can be enabled for custom tasks by getting additional properties as parameters for the custom tasks. Currently they need to be set via the source view. 

If we consider the example [creating custom task scheduling](https://mi.docs.wso2.com/en/latest/develop/customizations/creating-custom-task-scheduling/), here the user need to manually edit the synapse config to add the line `<property xmlns:task="http://www.wso2.org/products/wso2commons/tasks" name="stockFile" value="/path/to/stockfile.txt"/>` If we give a way to add new properties via the UI, we can eliminate the need of modifying the source.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by ChinthakaJ98** [comment]
The latest release v1.1.1 has resolved this issue. Please reopen if the problem persists.
