### ISSUE TITLE
SalesforceBulk connection properties are not showing after creation

### ISSUE THREAD

**Issue by chathuranga-jayanath-99** [wso2/mi-vscode#272]
**Description:**
After initiating the SalesforceBulk connection, the values provided do not appear when checking the connection; the form appears empty. However, the entered values are present in the source view.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
v1.0.1

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by thuva9872** [comment]
This is fixed in the latest version (v1.0.5).
