### ISSUE TITLE
Edit form for message stores doesn't work properly when there are invalid values in the synapse code

### ISSUE THREAD

**Issue by ShammiL** [wso2/mi-vscode#275]
**Description:**
If a user provides an invalid value for a field in a message store through the synapse code and then tries to change something through the Edit form, the form doesn't work as expected. Even after changing a value, the "Update" button stays disabled. 

The field with the invalid value also doesn't show any error making it difficult for the user to find what he has done wrong.

https://github.com/user-attachments/assets/38233a55-3ff4-433a-993e-3fa0007bba02

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by thuva9872** [comment]
The latest release v1.0.5 has resolved the issue. Please reopen if the problem persists.
