### ISSUE TITLE
JMS API Version field in the Message store edit form doesn't retain value previously selected

### ISSUE THREAD

**Issue by ShammiL** [wso2/mi-vscode#276]
**Description:**
If a user selects a value form the JMS API Version dropdown in the message store edit form, the synapse code gets updated accordingly. But if the edit form is opened again, the previously selected value is not retained.

https://github.com/user-attachments/assets/da61049f-2e7e-414b-bfac-70795e0a15d5

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by gigara** [comment]
The latest release v1.1.0 has resolved the issue. Please reopen if the problem persists.
