### ISSUE TITLE
Typo in WSDL Resources section in Edit Proxy form

### ISSUE THREAD

**Issue by chathuranga-jayanath-99** [wso2/mi-vscode#277]
**Description:**
In the `Edit Proxy` form under `Advanced Options`, the option to add a WSDL resource is labeled as `+ Add WSDL Policy`. It would be more accurate to change this to `+ Add WSDL Resource`.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
v1.0.1

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by gigara** [comment]
The latest release v1.1.0 has resolved the issue. Please reopen if the problem persists.
