### ISSUE TITLE
Required fields for adding a WSDL resource to a proxy service are not being validated correctly.

### ISSUE THREAD

**Issue by chathuranga-jayanath-99** [wso2/mi-vscode#278]
**Description:**
After creating a proxy service, when attempting to add a WSDL resource, the Location and Key fields are marked as required. However, these fields are not validated properly, allowing the addition of a WSDL resource with empty Location and Key values.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
v1.0.1

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by ChinthakaJ98** [comment]
ParamManager component related validation issues are being tracked in https://github.com/wso2/mi-vscode/issues/400
