### ISSUE TITLE
The try out feature for proxy services does not work

### ISSUE THREAD

**Issue by ShammiL** [wso2/mi-vscode#28]
**Description:**
The "Try out" button for Proxy services does not work.

<img width="1194" alt="image" src="https://github.com/wso2/mi-vscode/assets/47134017/f8992f13-4743-4951-b4c8-fe0ce701d08d">
Clicking on the Try out button gives no results.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by sachiniSam** [comment]
Try-it option is currently not present for the proxy as the swagger view is not supported. Therefore try-it button has been removed.
