### ISSUE TITLE
Function disappears in the mapping expressions in VSCode

### ISSUE THREAD

**Issue by poorna2152** [wso2/mi-vscode#283]
**Description:**
Consider the following video. Here the requirement is to uppercase the value in the output. When the output is selected to add a expression and then when the function is selected in the expression tab, the function disappears. Still  in the `ts` code the function call added.

![issue2](https://github.com/user-attachments/assets/fb4f025e-d94f-4355-9038-0358b9ebec57)

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by ChinthakaJ98** [comment]
The latest release v1.1.1 has resolved this issue. Please reopen if the problem persists.
