### ISSUE TITLE
The placeholders in the additional properties section in an endpoint creation form needs to be manually deleted

### ISSUE THREAD

**Issue by ShammiL** [wso2/mi-vscode#286]
**Description:**
The placeholders in the additional properties section in an endpoint creation form needs to be manually deleted before entering new values.

![image](https://github.com/user-attachments/assets/4b40917e-31cf-42bf-8e60-fde09a5e7caa)

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by gigara** [comment]
The latest release v1.1.0 has resolved the issue. Please reopen if the problem persists.
