### ISSUE TITLE
Adding a namespace for `Fast Xslt Dynamic SchemaKey` in `Fast XSLT` Mediator doesn't get saved. 

### ISSUE THREAD

**Issue by chathuranga-jayanath-99** [wso2/mi-vscode#289]
**Description:**
After adding a namespace for the Fast XSLT Dynamic SchemaKey and saving the Fast XSLT Mediator, the namespace does not get saved properly. When revisiting the mediator, the namespace is missing.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
v1.0.1

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by thuva9872** [comment]
The latest release v1.0.3 has resolved the issue. Please reopen if the problem persists.
