### ISSUE TITLE
No option to select the sequence or proxy in Task creation form

### ISSUE THREAD

**Issue by SanojPunchihewa** [wso2/mi-vscode#290]
**Description:**

In the latest MI extensions, there is no option to select the sequence name or proxy name in Task creation form.

<img width="680" alt="Screenshot 2024-08-01 at 08 53 20" src="https://github.com/user-attachments/assets/1b14a88c-f6c5-4d55-99a4-1d33a9dc336a">

However, in an older extension version `0.9.24072507` the option to select the sequence is available as follows.

<img width="678" alt="Screenshot 2024-08-01 at 08 52 27" src="https://github.com/user-attachments/assets/3c9f0432-99c9-436d-8901-ce8633d823b2">

**Comment by gigara** [comment]
@SanojPunchihewa Sequence/proxy names are now generated automatically based on the task name. You don't need to worry about it as it is handled internally.

**Comment by SanojPunchihewa** [comment]
Usually users may first try out the sequence or proxy and then use the task to run it as a scheduled job. IMO we should let the user choose to select an existing one or create the sequence/proxy otherwise. @rosensilva WDYT?

**Comment by hevayo** [comment]
Yeh we should be able to select a sequence name if required. Did we purposely remove this ? 

Instead there should be a check box to say create a new sequence automatically.

**Comment by thuva9872** [comment]
@SanojPunchihewa , Shall we close this as it is fixed in the latest version (v1.0.5) ?
