### ISSUE TITLE
No option to add schema in "Schemas" table in Validate mediator

### ISSUE THREAD

**Issue by thuva9872** [wso2/mi-vscode#291]
**Description:**
<img width="448" alt="image" src="https://github.com/user-attachments/assets/c1f864f3-0c9b-4459-9de0-07af7be810e6">

This was supposed to show a dropdown of available schemas.
"Location Key" in "Location" table also missing.

**Comment by gigara** [comment]
The latest release v1.0.3 has resolved the issue. Please reopen if the problem persists.
