### ISSUE TITLE
No option to select sequence/endpoint in Clone mediator

### ISSUE THREAD

**Issue by thuva9872** [wso2/mi-vscode#292]
**Description:**
When adding a new target in Clone mediator, if we select the `Sequence Type` as `REGISTRY_REFERENCE`, it should show a dropdown of available sequences. But this option is missing. Same for the `Endpoint Type` too.
<img width="450" alt="image" src="https://github.com/user-attachments/assets/ab7a048d-d8a6-4922-b626-e6df2a5b0502">

**Comment by gigara** [comment]
The latest release v1.0.3 has resolved the issue. Please reopen if the problem persists.
