### ISSUE TITLE
Fast XSLT mediator dropdown not displaying XSLT and XSL registry resources

### ISSUE THREAD

**Issue by chathuranga-jayanath-99** [wso2/mi-vscode#297]
**Description:**
When creating a Fast XSLT Mediator, the dropdown for selecting the `Fast XSLT Static SchemaKey` for `Static` schema type should list available XSLT and XSL registry resources. However, none of the added XSLT and XSL resources are appearing in the dropdown.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
v1.0.2

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
1. Add registry resources for XSL and XSLT types.
2. Add a Fast XSLT Mediator.
3. Attempt to select a `Fast XSLT Static SchemaKey` from the dropdown menu.

**Related Issues:**

**Comment by thuva9872** [comment]
The latest release v1.0.5 has resolved the issue. Please reopen if the problem persists.
