### ISSUE TITLE
Fix typo

### ISSUE THREAD

**Issue by kalaiyarasiganeshalingam** [wso2/mi-vscode#30]
**Description:**
 `Refering Sequence` has a typo. 
<img width="526" alt="Screenshot 2024-07-02 at 15 06 04" src="https://github.com/wso2/mi-vscode/assets/12771261/3e31f1bb-16aa-4070-be78-cacfe1adfbbb">

**Comment by thuva9872** [comment]
The latest pre-release v0.9.24072507 has resolved the issue. Please reopen if the problem persists.
