### ISSUE TITLE
Empty form generated when trying to add parameters to a sql statement in the DB Report mediator

### ISSUE THREAD

**Issue by poorna2152** [wso2/mi-vscode#301]
**Description:**
In the DB report mediator after an sql statement is added and when trying to add parameters to the statement an empty form is generated.

<img width="683" alt="Screenshot 2024-08-02 at 09 35 11" src="https://github.com/user-attachments/assets/ca17f9d8-2429-4be3-ad32-95e1f8f726d1">

**Comment by thuva9872** [comment]
The latest release v1.0.5 has resolved the issue. Please reopen if the problem persists.
