### ISSUE TITLE
DB Report mediator form fields `Connection DB Type` and  `Database Configuration` resets when trying to edit the form

### ISSUE THREAD

**Issue by poorna2152** [wso2/mi-vscode#303]
**Description:**
When the `Connection DB Type` field in the DB Report mediator is set to MYSQL and the form is submitted when trying to edit the form again the value of that field is reset to `Other`. Similar behaviour is observed with the `Database Configuration` field. When a value to that field is provided and when trying to edit the mediator again the value of that field is reset.

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by thuva9872** [comment]
The latest release v1.0.5 has resolved the issue. Please reopen if the problem persists.
