### ISSUE TITLE
Trying to open an existing Inbound opens the injecting sequence

### ISSUE THREAD

**Issue by SanojPunchihewa** [wso2/mi-vscode#306]
**Description:**

We we try to open an existing inbound by clicking it in the project explorer panel, the injecting sequence will be open. To edit it, the user will need to explicitly click the "Edit" button on top of the sequence view.

https://github.com/user-attachments/assets/9b0103d4-ea07-43fc-a467-069632018a14

**Comment by kaumini** [comment]
This should be the expected flow in user point of view. WDYT @hevayo

**Comment by SanojPunchihewa** [comment]
If the user wants to edit the sequence, he may directly open the sequence. In IMO, opening the sequence when the user wants to do some change to the inbound config is wrong. Furthermore this was observed in the latest plugin versions, previously it opened the Inbound edit form when we click an inbound.
