### ISSUE TITLE
Export action always prompts for a location

### ISSUE THREAD

**Issue by ShammiL** [wso2/mi-vscode#308]
**Description:**
When a user hits the Export button in the MI Overview Window, he is always prompted for the location. This can be somewhat annoying if the user has to export multiple times and is expected to select the location each time. This can be made easier for the user if the default export location and/or the last location provided by the user is also shown for the user to select from.

<img width="1200" alt="image" src="https://github.com/user-attachments/assets/fe39650a-1b2c-4259-94c0-72b69e7604e7">

**Describe your problem(s)**

**Describe your solution(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by thuva9872** [comment]
Related Issue: https://github.com/wso2/mi-vscode/issues/280

**Comment by thuva9872** [comment]
The latest release v1.1.1 has resolved this issue. Please reopen if the problem persists.
