### ISSUE TITLE
Misalignment in text and design view's `+` sign in `Switch` mediator.

### ISSUE THREAD

**Issue by chathuranga-jayanath-99** [wso2/mi-vscode#310]
**Description:**
When creating cases in the `Switch` mediator, if a long text is provided for the `case regex`, the text in the case branch and the `+` sign in the design view become misaligned, as shown in the image below.
<img width="750" alt="Screenshot 2024-08-02 at 09 13 28" src="https://github.com/user-attachments/assets/2ca150de-2a6c-4df2-8f94-6bc741a7d4ee">

**Product Version**
v1.0.3

**Describe your problem(s)**

**Describe your solution(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by gigara** [comment]
The latest release v1.1.1 has resolved the issue. Please reopen if the problem persists.
