### ISSUE TITLE
Introduce a placeholder instead of a default value for the added Parameters when creating a Sequence Template.

### ISSUE THREAD

**Issue by chathuranga-jayanath-99** [wso2/mi-vscode#311]
**Description:**
There is a default value for newly adding parameters to a sequence template with the value `parameter_value`. It can be changed into a placeholder. 

**Identified Version**
v1.0.3

**Describe your problem(s)**

**Describe your solution(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by ChinthakaJ98** [comment]
The latest release v1.1.1 has resolved this issue. Please reopen if the problem persists.
