### ISSUE TITLE
For the `Inline` payload format, changing the `Media Type` does not update the placeholder in the payload field.

### ISSUE THREAD

**Issue by chathuranga-jayanath-99** [wso2/mi-vscode#315]
**Description:**
In Payload Factory mediator when the `Payload Format` is set to `Inline`, users can enter the payload directly. By default, the placeholder in the payload field displays a sample JSON object. However, when the `Media Type` is changed, the placeholder should update to reflect the appropriate format for the selected media type. Currently, the placeholder does not change accordingly.

**Steps to reproduce:**

**Affected Versions:**
v1.0.3

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by thuva9872** [comment]
The latest release v1.0.5 has resolved the issue. Please reopen if the problem persists.
