### ISSUE TITLE
In the `Call` mediator, the `Select Endpoint` dropdown does not require a button to indicate an expression (`Ex`).

### ISSUE THREAD

**Issue by chathuranga-jayanath-99** [wso2/mi-vscode#316]
**Description:**
$subject

**Identified Version**
v1.0.3

**Describe your problem(s)**

**Describe your solution(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by thuva9872** [comment]
The latest release v1.0.5 has resolved the issue. Please reopen if the problem persists.
