### ISSUE TITLE
When adding arguments to a `Payload Factory` mediator, the `Evaluator` field is only needed if the value is an expression.

### ISSUE THREAD

**Issue by chathuranga-jayanath-99** [wso2/mi-vscode#317]
**Description:**
$subject

**Steps to reproduce:**

**Affected Versions:**
v1.0.3

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by thuva9872** [comment]
The latest release v1.0.5 has resolved the issue. Please reopen if the problem persists.
