### ISSUE TITLE
`INLINE` capability to define a `Call Endpoint` can be improved.   

### ISSUE THREAD

**Issue by chathuranga-jayanath-99** [wso2/mi-vscode#318]
**Description:**
In the `Inline Endpoint`, placeholder only says `Define your endpoint as an XML`, but that is not very understanding enough, which is expected here. 

Because it can be only the URI part as below or the whole endpoint definition. 
`<address uri="http://sample.com">`

**Identified Version**
v1.0.3

**Describe your problem(s)**

**Describe your solution(s)**
If we can show a placehodler, which indicates the expected input format, it might help to resolve this issue. 

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by thuva9872** [comment]
The Inline Endpoint option is not being promoted to users and is hidden from new users. This field is included only for backward compatibility purposes. As we are closing this issue, no further action is required.
