### ISSUE TITLE
Adding wrong inline endpoint definition, doesn't allow to edit the `Call` mediator.

### ISSUE THREAD

**Issue by chathuranga-jayanath-99** [wso2/mi-vscode#319]
**Description:**
When adding an `INLINE Endpoint` let's say you add a endpoint definition as below, without the closing endpoint tag. 
```xml
<endpoint name="SampleEp" xmlns="http://ws.apache.org/ns/synapse">
    <address uri="http://sample.com"/>
```
Then if you try to edit the `Call` mediator, it won't open the edit window. 

**Steps to reproduce:**

**Affected Versions:**
v1.0.3

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by thuva9872** [comment]
The latest release v1.0.5 has resolved the issue. Please reopen if the problem persists.
