### ISSUE TITLE
'Action' option is missing in the XSLT mediator edit view

### ISSUE THREAD

**Issue by gabilang** [wso2/mi-vscode#320]
**Description:**

The `Action` option was there in the integration studio to allow the property to be removed from the XSLT script if required. But the mi-vscode extension does not have that option. 
Is it an intentional change? 

![Screenshot 2024-08-05 at 08 11 13](https://github.com/user-attachments/assets/d21c822c-ad6a-448c-a834-27a50f6327b1)

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by thuva9872** [comment]
This property is not supported by the mediator. The mediator catalog has been updated. Therefore, we are closing this issue.
