### ISSUE TITLE
XSLT mediator edit view does not have a field to set the key type

### ISSUE THREAD

**Issue by gabilang** [wso2/mi-vscode#321]
**Description:**

XSLT mediator form view does not have a field to set the type of keys: The type of keys should be selected between `Static Key` and `Dynamic` as per the XSLT mediator catalog. 

![Screenshot 2024-08-05 at 08 17 25](https://github.com/user-attachments/assets/c90dca46-f1b7-40fb-a4e3-b526ffe558b3)

Edit the XSLT mediator catalog if this field is not necessary now. 

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by thuva9872** [comment]
Hi @gabilang,

We don't need a separate field to set the key type. We can toggle the expression (Ex) button to enter a dynamic key in the `XSLT Schema Key`.

Thanks,
Thuvarakan

**Comment by gabilang** [comment]
> Hi @gabilang,
> 
> We don't need a separate field to set the key type. We can toggle the expression (Ex) button to enter a dynamic key in the `XSLT Schema Key`.
> 
> Thanks, Thuvarakan

Thanks for the clarification. Then we need to remove the first row from the table in the [XSLT Mediator catalog](https://mi.docs.wso2.com/en/latest/reference/mediators/xslt-mediator/#configuration)

**Comment by gabilang** [comment]
Closing this since the change is intentional.
