### ISSUE TITLE
Adding an incorrect element for the inline definition of Call mediator cause unexpected behaviour. 

### ISSUE THREAD

**Issue by chathuranga-jayanath-99** [wso2/mi-vscode#322]
**Description:**
After defining **Call** mediator with a wrong XML element. Like below,
```xml
<ep>SampleEp<ep/>
```
If we try to update the **Call** mediator with below XML element. 
```xml
<endpoint key="SampleEp"/>
```
The resulting source view of the **Call** mediator will be as shown below, which is incorrect. 
```xml
<call>
	<ep>SampleEp<ep/>
	<endpoint key="fix"/>
</call>
```

**Steps to reproduce:**
1. Define a **Call** mediator with a wrong XML element.
2. Then update the **Call** mediator with another XML element. 
3. Check the source view. 

**Affected Versions:**
v1.0.3

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by thuva9872** [comment]
Related Issue: https://github.com/wso2/mi-vscode/issues/319

**Comment by thuva9872** [comment]
The latest release v1.0.5 has resolved the issue. Please reopen if the problem persists.
