### ISSUE TITLE
Scheduled message forwarding processor create form doesn't mandate the message store field

### ISSUE THREAD

**Issue by ShammiL** [wso2/mi-vscode#324]
**Description:**
When a user creates a Scheduled message processing store, he is not required to provide the message store. Hence, when the message processor is created, the field `messageStore` is left empty. If the user happens to run the code as it is, he will run in to a Null Pointer Exception due to the missing message store. 

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by thuva9872** [comment]
The latest pre-release v1.1.0 has resolved the issue. Please reopen if the problem persists.
