### ISSUE TITLE
Once created, connections cannot be deleted through the VSCode plugin

### ISSUE THREAD

**Issue by ShammiL** [wso2/mi-vscode#325]
**Description:**
Once a user creates a connection, it cannot be deleted through the VS Code plugin.
![image](https://github.com/user-attachments/assets/3e668ec9-f1e7-4018-b437-365415c9a37d)

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by kaumini** [comment]
The latest release v1.1.1 has resolved the issue. Please reopen if the problem persists.
