### ISSUE TITLE
Improve sequence creation UX of inbound Endpoint creation form

### ISSUE THREAD

**Issue by kaumini** [wso2/mi-vscode#326]
**Description:**
- [ ]  Sequence field should be a dropdown with available sequences
- [ ]  User should provided with a checkbox to automatically generate new sequence 

**Describe your problem(s)**

**Describe your solution(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by gigara** [comment]
The latest release v1.1.0 has resolved the issue. Please reopen if the problem persists.
