### ISSUE TITLE
Available endpoints should be listed under `Static` when adding endpoints for a `Load Balance Endpoint`.

### ISSUE THREAD

**Issue by chathuranga-jayanath-99** [wso2/mi-vscode#327]
**Description:**
Currently, to add available endpoints to the `Load Balance Endpoint`, we have to manually type the name of the endpoint. It would be better if we could provide a dropdown list of the available endpoints.

**Identified Version**
v1.0.3

**Describe your problem(s)**

**Describe your solution(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by ChinthakaJ98** [comment]
The latest release v1.1.1 has resolved this issue. Please reopen if the problem persists.
