### ISSUE TITLE
Creating a new Message Store form with ActiveMQ default values gives validation errors.

### ISSUE THREAD

**Issue by KalinduGandara** [wso2/mi-vscode#328]
**Description:**
<img width="1136" alt="Screenshot 2024-08-08 at 11 49 42" src="https://github.com/user-attachments/assets/1df798af-4a10-4a75-81ef-b5004ffc9514">

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by thuva9872** [comment]
Related Issue: https://github.com/wso2/mi-vscode/issues/263

**Comment by thuva9872** [comment]
The latest release v1.0.5 has resolved the issue. Please reopen if the problem persists.
