### ISSUE TITLE
Show download progress of inbound endpoint connectors

### ISSUE THREAD

**Issue by kaumini** [wso2/mi-vscode#329]
**Description:**
Some inbound connectors take longer for download. It is better to show download progress

**Describe your problem(s)**

**Describe your solution(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by gigara** [comment]
The latest release v1.1.0 has resolved the issue. Please reopen if the problem persists.
