### ISSUE TITLE
Project name creation - Project name cannot contain spaces or special characters  

### ISSUE THREAD

**Issue by Heinrich24** [wso2/mi-vscode#330]
**Description:** 

When using the extension to generate a project I am prompted with an error that I cannot generate a project name with either "-" (hyphen) or "_" (underscore) due to it being a special character.  

I understand that these are special characters, but it is quite standard to generate project names with either a hyphen or underscore. This is also relevant to artifact and groupId's  

**Describe your problem(s)** 

I am not able generate a project name that contains either "-" (hyphen) or "_" (underscore) as it is not allowed because it is considered a special character.  

**Describe your solution(s)** 

Thus, my recommendation is to allow these special characters "-" (hyphen) or "_" (underscore) when creating a project name. This is also applicable to artifact and groupId's.

**Comment by Heinrich24** [comment]
![afbeelding](https://github.com/user-attachments/assets/37974ac3-f751-4a1e-9723-403c548dc8b6)

**Comment by Boontjes** [comment]
![image](https://github.com/user-attachments/assets/4f8f715d-54d5-45cf-8143-b60265f06b29)
same for Group Id and Artifact id, they should support hyphens and underscore as specials chars.

**Comment by thuva9872** [comment]
Duplicate Issue: https://github.com/wso2/mi-vscode/issues/115

**Comment by thuva9872** [comment]
The latest pre-release v1.1.0 has resolved the issue. Please reopen if the problem persists.
