### ISSUE TITLE
Added connection's source view is not formatted correctly

### ISSUE THREAD

**Issue by chathuranga-jayanath-99** [wso2/mi-vscode#334]
**Description:**
When a connection is added, its source view is not formatted correctly, as shown below.
```xml
<?xml version="1.0" encoding="UTF-8"?>
    <localEntry key="FileConnection" xmlns="http://ws.apache.org/ns/synapse">
        <file.init>
  <connectionType>LOCAL</connectionType>
  <name>FileConnection</name>
  <workingDir>/Users/chathurangaj/Desktop/resource</workingDir>
  <fileLockScheme>Local</fileLockScheme>
</file.init>
    </localEntry>
```

**Describe your problem(s)**

**Describe your solution(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by gigara** [comment]
The latest release v1.1.0 has resolved the issue. Please reopen if the problem persists.
