### ISSUE TITLE
Mapping arrays in the data mapper is not intuitive. 

### ISSUE THREAD

**Issue by chathuranga-jayanath-99** [wso2/mi-vscode#335]
**Description:**
Currently, when mapping two arrays of objects, you need to first map the arrays and then click the bulb icon to drill down and map the fields within the objects. This process can be improved.
![Screenshot 2024-08-11 at 19 17 33](https://github.com/user-attachments/assets/4feece9d-9691-4e25-b0d6-2bbb854a62d9)

**Describe your problem(s)**

**Describe your solution(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by madushajg** [comment]
We have improved this UX with https://github.com/wso2-enterprise/vscode-extensions/pull/3560
