### ISSUE TITLE
The diagram for rest api with a handler is not rendered

### ISSUE THREAD

**Issue by poorna2152** [wso2/mi-vscode#34]
**Description:**
When the code given in the following sample is added to the vscode the diagram is not rendered. After the handler is removed it is rendered properly. https://mi.docs.wso2.com/en/4.3.0/learn/examples/rest-api-examples/securing-rest-apis/

**Comment by thuva9872** [comment]
The diagram is rendered correctly when the handler has property. If there is no property, it is throwing error.

**Comment by gigara** [comment]
It's working for me.
<img width="1449" alt="image" src="https://github.com/user-attachments/assets/d5bc7248-74b1-4b11-bb11-27a0efb93690">

@poorna2152 Can you attach the code to reproduce?

**Comment by thuva9872** [comment]
Hi @gigara ,

 The diagram is rendering without any errors. But the service designer is not working for the same code that you used.

Thanks,
Thuvarakan

**Comment by gigara** [comment]
The latest pre-release v0.9.24072507 has resolved the issue. Please reopen if the problem persists.
