### ISSUE TITLE
Can't add mediators to fault window. 

### ISSUE THREAD

**Issue by chathuranga-jayanath-99** [wso2/mi-vscode#340]
**Description:**
Selecting the `Fault` option and adding a log mediator will not add the mediator to the flow except it will appear same as the initial view and window is changed from `Fault` to `Flow`.
Additionally, it displays incorrect XML content in the source view, as shown below.

```xml
<?xml version="1.0" encoding="UTF-8"?>
<proxy name="test" startOnLoad="true" transports="http https" xmlns="http://ws.apache.org/ns/synapse">
	<target>
		<inSequence>
		</inSequence>
		<outSequence>
		</outSequence>
		<faultSequence/>
		<log category="INFO" level="simple"/>
	</target>
</proxy>
```

**Steps to reproduce:**

**Affected Versions:**
v1.0.4

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by thuva9872** [comment]
Duplicate: https://github.com/wso2/mi-vscode/issues/50
