### ISSUE TITLE
Allow creating `Send` and `Call` mediators with endpoint specified as None

### ISSUE THREAD

**Issue by poorna2152** [wso2/mi-vscode#344]
It should be able to create `Call` and `Send` mediators with endpoint being None as per the [documentation](https://mi.docs.wso2.com/en/latest/reference/mediators/call-mediator/).
This is not supported in the VsCode now.

**Comment by thuva9872** [comment]
The latest release v1.0.5 has resolved the issue. Please reopen if the problem persists.
