### ISSUE TITLE
Load balance endpoint form doesn't validate inline endpoint xml

### ISSUE THREAD

**Issue by KalinduGandara** [wso2/mi-vscode#345]
**Description:**
In the Load Balance Endpoint form, any text can be added as an inline endpoint without validating the XML. If invalid XML is added and the file is saved, the form will not correctly display the endpoint value the next time it is opened.

> **Note :** Local entry XML form has this validation.

<img width="634" alt="Screenshot 2024-08-13 at 16 33 15" src="https://github.com/user-attachments/assets/4efa6cdd-436e-4368-80f3-c8c748e654c4">

**Describe your problem(s)**

**Describe your solution(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by thuva9872** [comment]
The inline is just for backward compatibility. We do not encourage users to use it.
