### ISSUE TITLE
In the Validate mediator, the Schemas dropdown does not display available Local Entries.

### ISSUE THREAD

**Issue by KalinduGandara** [wso2/mi-vscode#346]
**Description:**
$subject
<img width="887" alt="Screenshot 2024-08-14 at 16 24 17" src="https://github.com/user-attachments/assets/9e05e84b-e97d-4177-95b4-51269abe6c07">

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by thuva9872** [comment]
The latest pre-release v1.1.0 has resolved the issue. Please reopen if the problem persists.
