### ISSUE TITLE
Sequence edit form does not show onError sequences properly

### ISSUE THREAD

**Issue by KalinduGandara** [wso2/mi-vscode#348]
**Description:**

https://github.com/user-attachments/assets/47226775-df60-4c59-946d-205a5b978868

**Describe your problem(s)**
The form does not display in full page, so when a dropdown has more than three values, the last values are not visible. The user needs to scroll the form to see the last values.
**Describe your solution(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by gigara** [comment]
The latest pre-release v1.1.0 has resolved the issue. Please reopen if the problem persists.
