### ISSUE TITLE
Improve Data Mapper Expression Editor

### ISSUE THREAD

**Issue by rosensilva** [wso2/mi-vscode#352]
**Description:**

Using the enter key to select an item from the dropdown menu is more intuitive. Should we modify the functionality to allow the enter key for item selection in the screenshot?

<img width="986" alt="Screenshot 2024-08-16 at 10 46 56" src="https://github.com/user-attachments/assets/39daa5c7-ef61-470f-a974-a03b095cbfec">

**Comment by ChinthakaJ98** [comment]
The latest release v1.1.1 has resolved this issue. Please reopen if the problem persists.
