### ISSUE TITLE
Should not be possible to create a `Reception List Endpoint` without including any endpoints.

### ISSUE THREAD

**Issue by chathuranga-jayanath-99** [wso2/mi-vscode#353]
**Description:**
Currently it is possible to create a `Reception List Endpoint` without adding any endpoints. 

**Steps to reproduce:**

**Affected Versions:**
v1.0.4

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by gigara** [comment]
The latest release v1.1.0 has resolved the issue. Please reopen if the problem persists.
