### ISSUE TITLE
Improve UX by Stoping Auto-scrolling in Copilot Window when User Scrolls up

### ISSUE THREAD

**Issue by viggnah** [wso2/mi-vscode#358]
**Description:**
When you ask a question, Copilot starts printing the answer and starts auto-scrolling down after reaching the end of the page. But if I scroll up to start reading the answer, Copilot keeps pulling you down with auto-scroll. So you have to wait till the answer is complete before you can go up and start reading again. This is super annoying. 

**Describe your solution(s)**
Stop the downwards auto-scrolling the moment the user scrolls up while the answer is printing. This is the default behaviour in ChatGPT, Gemini etc. Otherwise it's just annoying. 

**Suggested Labels (optional):**
Area/AI

**Comment by ChinthakaJ98** [comment]
The latest release v1.1.1 has resolved this issue. Please reopen if the problem persists.
