### ISSUE TITLE
[DataMapper] Mapping conditions getting corrupted after initialising an array element 

### ISSUE THREAD

**Issue by isuruh15** [wso2/mi-vscode#359]
**Description:**
We have came across $subject when trying to map a single element to an attribute of an array element. (see the attached screen-recording.)
It also observed that once the array element is initialised, can't select a element in the input schema too. We have to click on the canvas and again click on the element to select.

https://github.com/user-attachments/assets/5f8f830a-f481-4b55-8023-c700b4b28836

**Comment by KCSAbeywickrama** [comment]
Fixed with https://github.com/wso2-enterprise/vscode-extensions/pull/3686

**Comment by gigara** [comment]
The latest release v1.1.0 has resolved the issue. Please reopen if the problem persists.
