### ISSUE TITLE
Add Artifact has no Option for Data Service

### ISSUE THREAD

**Issue by viggnah** [wso2/mi-vscode#360]
**Description:**
![Screenshot 2024-08-23 at 4 52 01 PM](https://github.com/user-attachments/assets/e91b4bb4-1c66-437c-9d89-3d62492d4405)

**Steps to reproduce:**
Click "Add Artifact"
There seems to be no option to create data service...

**Affected Versions:**
1.0.4

**OS, DB, other environment details and versions:**
MacOS 14.4.1 (23E224)

**Comment by gigara** [comment]
The latest release v1.1.0 has resolved the issue. Please reopen if the problem persists.
