### ISSUE TITLE
Parameter values are getting encoded in connection form

### ISSUE THREAD

**Issue by thuva9872** [wso2/mi-vscode#363]
**Description:**
When we enter xml/CDATA value in connector connection form, the values are getting encoded.

**Steps to reproduce:**
1. Open a connection form.
2. Give `<![CDATA[some stuff]]>` 
3. Create/Update the connection form.
4. The value will be encoded in the file.

**Comment by kaumini** [comment]
The latest release v1.1.1 has resolved the issue. Please reopen if the problem persists.
