### ISSUE TITLE
Connector operation edit form is not shown for operation names with a dot

### ISSUE THREAD

**Issue by SanojPunchihewa** [wso2/mi-vscode#364]
**Description:**

When we have a connector operation like `googleAdNetwork.customers.createCustomerClient`, when initially adding the operation, the operation form view is shown properly[1]. However when we try to edit that inserted operation, only the connection is shown in the edit form[2].

[1] - 
<img width="464" alt="Screenshot 2024-08-29 at 08 49 00" src="https://github.com/user-attachments/assets/846834ae-0e46-45bd-a8f2-324af497e156">

[2] - 
<img width="1114" alt="Screenshot 2024-08-29 at 08 49 22" src="https://github.com/user-attachments/assets/56df4df2-96ff-460d-bfc3-d34b0c92b662">

**Comment by kaumini** [comment]
The latest release v1.1.1 has resolved the issue. Please reopen if the problem persists.
