### ISSUE TITLE
Not way to configure the namespaces to the store mediator in vscode

### ISSUE THREAD

**Issue by kalaiyarasiganeshalingam** [wso2/mi-vscode#37]
**Description:**
As per this [doc](https://ei.docs.wso2.com/en/latest/micro-integrator/references/mediators/store-Mediator/),   we can enable the dynamic route messages to a Message Store by giving a path expression (followed by its namespace definitions) for the value of the store name attribute. 

But there is no  way to configure the namespace of this in the vs code

```
<store messageStore="{$func:message_store/ns1:store/ns1:request/ns2:storeName}" xmlns:ns1="http://services.samples" xmlns:ns2="http://services.samples/ns2"/>
```

<img width="528" alt="Screenshot 2024-07-03 at 14 22 58" src="https://github.com/wso2/mi-vscode/assets/12771261/fec6d72c-cb2f-48ba-a226-05ac0a096020">

**Comment by thuva9872** [comment]
The latest release v1.0.2 has resolved the issue. Please reopen if the problem persists.
