### ISSUE TITLE
MI runtime version property is missing in new Integration Projects

### ISSUE THREAD

**Issue by rosensilva** [wso2/mi-vscode#371]
**Description:**
In the Integration Studio when creating an integration project following properties are added to pom.xml

```
  <properties>
    <project.scm.id>integration-project</project.scm.id>
    <project.runtime.version>4.3.0</project.runtime.version>
  </properties>
```
There is a backward compatibility issue for Choreo without this property

**Comment by ChinthakaJ98** [comment]
The latest release v1.1.0 has resolved this issue. Please reopen if the problem persists.
