### ISSUE TITLE
Cannot add registry properties or metadata

### ISSUE THREAD

**Issue by GDLMadushanka** [wso2/mi-vscode#375]
**Description:**
We need a mechanism to add registry properties and registry metadata from the VSCode extension. 

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by ChinthakaJ98** [comment]
The latest release v1.1.1 has resolved this issue. Please reopen if the problem persists.
