### ISSUE TITLE
Cannot build Docker Image in Windows OS

### ISSUE THREAD

**Issue by SanduniU** [wso2/mi-vscode#380]
**Description:**
Following error occurs when building the docker image in Windows OS:
```
[ERROR] Failed to execute goal org.wso2.maven:mi-container-config-mapper:5.2.60:config-mapper-parser (config-mapper-parser) on project HelloWorldService: Exception while parsing the deployment.toml file      
[ERROR] java.util.regex.PatternSyntaxException: Unexpected internal error near index 18
[ERROR] target\tmp_docker\

```
**Steps to reproduce:**

1. Create a new project in VS code(Use a sample project - Hello World Service)
2. Build the docker image

**Affected Versions:**

**OS, DB, other environment details and versions:**
Windows 10

**Comment by thuva9872** [comment]
The latest release v1.1.1 has resolved this issue. Please reopen if the problem persists.
