### ISSUE TITLE
Adding mediators to the inbound endpoint shows a misconnection.

### ISSUE THREAD

**Issue by chathuranga-jayanath-99** [wso2/mi-vscode#383]
**Description:**
After creating an HTTP inbound endpoint and adding a log mediator results in displaying the below sequence. 
<img width="1110" alt="Screenshot 2024-09-07 at 14 10 05" src="https://github.com/user-attachments/assets/0887379f-8799-41ff-9545-0b51843dd14b">

**Steps to reproduce:**

**Affected Versions:**
1.1.0

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by gigara** [comment]
The latest release v1.1.1 has resolved the issue. Please reopen if the problem persists.
