### ISSUE TITLE
Tail the output log for MI Server

### ISSUE THREAD

**Issue by pcnfernando** [wso2/mi-vscode#386]
**Description:**
Can we have automatic scroll down on the output console in the MI plugin?

**Describe your problem(s)**

**Describe your solution(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by thuva9872** [comment]
Hi @pcnfernando ,

We can toggle the auto scrolling in the output console. Please refer to the image attached below.
<img width="1122" alt="image" src="https://github.com/user-attachments/assets/e02e6f3f-50c0-411e-8171-629e4df54abc">

**Comment by pcnfernando** [comment]
Awesome. thanks for the prompt response
