### ISSUE TITLE
contentType attribute cannot be configured in file connector read operation

### ISSUE THREAD

**Issue by DedunuKarunarathne** [wso2/mi-vscode#387]
**Description:**
There is no field to add the `contentType` attribute in  file connector read operation

**Comment by ChinthakaJ98** [comment]
This issue occurs as we do not support the "NOT" condition currently in the connector form generator. Therefore we might need to update it accordingly to overcome this issue.

**Comment by kaumini** [comment]
The latest release v1.1.1 has resolved the issue. Please reopen if the problem persists.
