### ISSUE TITLE
[Data Mapper Mediator] Add ability to access specific array field elements in the Visualizer

### ISSUE THREAD

**Issue by YasanPunch** [wso2/mi-vscode#389]
**Description:**
Using the visual data mapper, it is only possible to map array fields to other array fields. It is needed to add the ability to access and map specific elements of an array field. 

Currently, implementing such a specific array element mapping from the ts code leads to broken visualization, 
<img width="1680" alt="Screenshot 2024-09-11 at 9 31 24 AM" src="https://github.com/user-attachments/assets/e9b53284-ec74-4d04-940d-fab5d2e1d970">

**Comment by KCSAbeywickrama** [comment]
This will further track with https://github.com/wso2/mi-vscode/issues/407

**Comment by ChinthakaJ98** [comment]
The latest release v1.1.1 has resolved this issue. Please reopen if the problem persists.
