### ISSUE TITLE
Some empty fields in RabbitMQ inbound endpoint creation form gives "invalid number" error

### ISSUE THREAD

**Issue by ShammiL** [wso2/mi-vscode#39]
**Description:**

The RabbitMQ inbound endpoint form has a "Connection" section which is by default collapsed. If the other required fields are filled and the inbound endpoint is created without expanding the "Connection" section, the creation will happen with no issues. But if the section is expanded, and no values are provided before hitting the Create button, the "Factory Heartbeat" and the "Connection Timeout" fields would show an "Invalid number" error as shown in below image.

![image](https://github.com/wso2/mi-vscode/assets/47134017/4801e0ec-e3c2-405d-bbeb-e01e5122bdfa)

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by ShammiL** [comment]
Noticed the same issue when creating a JMS inbound endpoint. The `Retry Duration` field in Resilience section is giving "Invalid number" error when that section is expanded but the field is left empty.

![image](https://github.com/wso2/mi-vscode/assets/47134017/0aeda709-bc5d-4903-af4a-c3293045bdaa)

**Comment by kaumini** [comment]
The latest release v1.0.1 has resolved the issue. Please reopen if the problem persists.
