### ISSUE TITLE
Endpoint popup form is missing close button

### ISSUE THREAD

**Issue by kaumini** [wso2/mi-vscode#390]
**Description:**

https://github.com/user-attachments/assets/734b2db0-b03c-4ce5-bc59-6938b53f422d

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by ChinthakaJ98** [comment]
Also we are getting directed back to the Project Overview page when we create an endpoint from the diagram view within the Call Endpoint mediator. This ideally needs to be changed to be directed back the mediator side panel as it was opened from there. This also seems like an issue of the popup form.

**Comment by kaumini** [comment]
The latest release v1.1.1 has resolved the issue. Please reopen if the problem persists.
