### ISSUE TITLE
Non mandatory fields are marked as mandatory fields

### ISSUE THREAD

**Issue by Bhashinee** [wso2/mi-vscode#392]
**Description:**
When creating a Kafka connection, the following fields are marked as mandatory fields even though they are not mandatory fields for creating the Kafka connection.

<img width="668" alt="wrong-mandatory" src="https://github.com/user-attachments/assets/188ff2b5-de6d-461a-97d1-03ca60d09791">

As far as I saw these fields are mandatory only when creating a `secure kafka` connection. But right now I am creating a generic `kafka` connection. See the image below.

<img width="1086" alt="Mandatory-fields-kafka" src="https://github.com/user-attachments/assets/aa7a4367-eceb-4dab-b1c5-98ff3672b066">

**Steps to reproduce:**
Try to create a Kafka connection after importing the Kafka connector.

**Comment by kaumini** [comment]
The latest release v1.1.1 has resolved the issue. Please reopen if the problem persists.
