### ISSUE TITLE
Cannot create a new connection if the connectionName default value is missing in UI Schema

### ISSUE THREAD

**Issue by SanojPunchihewa** [wso2/mi-vscode#396]
**Description:**

When we have not defined a default value for the `connectionName` [1] in connector UI Schema, we though the user has provided a value for this mandatory field, the connection won't get created. Furthermore, it won't show any errors as well.

https://github.com/user-attachments/assets/f11bd741-1d41-456e-94fa-006fc50968f4

[1] - https://github.com/wso2-extensions/esb-connector-amazonsqs/blob/master/src/main/resources/uischema/connection.json#L13

**Comment by kaumini** [comment]
The latest release v1.1.1 has resolved the issue. Please reopen if the problem persists.
