### ISSUE TITLE
Discrepancy in the side navigation when more than one HTTP verb is set for a resource

### ISSUE THREAD

**Issue by SanojPunchihewa** [wso2/mi-vscode#398]
**Description:**

When more than one HTTP verb is set for a resource, only a cog wheel icon is shown in the side navigation. Is this the expected behaviour?

<img width="738" alt="Screenshot 2024-09-12 at 19 29 36" src="https://github.com/user-attachments/assets/eb5fc202-626a-4a80-92e5-1a27d1a8b0d8">

**Comment by ChinthakaJ98** [comment]
Hi @SanojPunchihewa,

As setting up multiple HTTP verbs for a single resource is not a common use case and as we have the option to maintain separate resources to support those HTTP verbs like below, this behaviour can be considered as expected.

<img width="335" alt="Screenshot 2024-09-23 at 09 51 11" src="https://github.com/user-attachments/assets/16de3afe-9515-4074-ac2d-adf5499a2604">

Therefore closing this issue after discussions considering the aforementioned.
