### ISSUE TITLE
Renaming the connection name of a connection adds a new connection

### ISSUE THREAD

**Issue by chathuranga-jayanath-99** [wso2/mi-vscode#406]
**Description:**
After creating a connection for a connector and renaming it will add a new connection. 

**Steps to reproduce:**

**Affected Versions:**
v1.1.0

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by kaumini** [comment]
The latest release v1.1.1 has resolved the issue. Please reopen if the problem persists.
