### ISSUE TITLE
Issue with Adding Numeric Values in Expressions When Generating Endpoints Templates in VS Code

### ISSUE THREAD

**Issue by kalaiyarasiganeshalingam** [wso2/mi-vscode#41]
**Description:**
Vscode is not allowed to add the value by using the expression which types are in the number when generating the endpoint template.

<img width="693" alt="Screenshot 2024-07-03 at 14 59 56" src="https://github.com/wso2/mi-vscode/assets/12771261/3fc51076-2792-443b-8f5f-0382b7ce8dc6">

**Comment by thuva9872** [comment]
The latest release v1.0.3 has resolved the issue. Please reopen if the problem persists.
