### ISSUE TITLE
Can add cases in switch mediator with empty value for case regex.

### ISSUE THREAD

**Issue by chathuranga-jayanath-99** [wso2/mi-vscode#412]
**Description:**
Adding a case with empty case regex will result in a source code as following:
```
<switch source="get-property('test')">
  <case regex=""></case>
  <default></default>
</switch>
```

**Steps to reproduce:**

**Affected Versions:**
v1.1.0

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by ChinthakaJ98** [comment]
The latest release v1.1.1 has resolved this issue. Please reopen if the problem persists.
