### ISSUE TITLE
Issue with Namespace Inclusion in Generated Endpoint Template Code in VS Code

### ISSUE THREAD

**Issue by kalaiyarasiganeshalingam** [wso2/mi-vscode#42]
**Description:**
When generating the endpoint template code using VS Code, the generated parameters include namespaces.
<img width="1267" alt="Screenshot 2024-07-03 at 14 51 44" src="https://github.com/wso2/mi-vscode/assets/12771261/8af8fceb-f773-4bf9-a404-139f9bf79fa1">

**Comment by thuva9872** [comment]
This is the expected behaviour.
