### ISSUE TITLE
Can't delete a created connection.

### ISSUE THREAD

**Issue by chathuranga-jayanath-99** [wso2/mi-vscode#421]
**Description:**
$subject

**Steps to reproduce:**

**Affected Versions:**
v1.1.0

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by kaumini** [comment]
Duplicate issue: https://github.com/wso2/mi-vscode/issues/325
