### ISSUE TITLE
Improper Rendering of the Log Edit Template UI

### ISSUE THREAD

**Issue by kalaiyarasiganeshalingam** [wso2/mi-vscode#43]
**Description:**
In this image, the value of the property and the edit and delete buttons are collapsed.
 
<img width="494" alt="Screenshot 2024-07-03 at 14 29 39" src="https://github.com/wso2/mi-vscode/assets/12771261/350e565c-7a80-49ae-9eae-c7bf8665e98d">

**Comment by thuva9872** [comment]
Follow this on: https://github.com/wso2/mi-vscode/issues/88
