### ISSUE TITLE
Implement method to generate data service from a datasource

### ISSUE THREAD

**Issue by anupama-pathirage** [wso2/mi-vscode#434]
Moving the issue  https://github.com/wso2-enterprise/mi-language-server/issues/156 by  [thuva9872](https://github.com/thuva9872)

**Description:**
Implement the method to support [this](https://mi.docs.wso2.com/en/latest/develop/creating-artifacts/data-services/creating-data-services/#generate-data-service-from-a-datasource) feature.

<img width="1072" alt="image" src="https://github.com/user-attachments/assets/d10f18ac-31bb-4d22-b9b3-f4a481054b17">

**Comment by ChinthakaJ98** [comment]
The latest release v1.1.1 has resolved this issue. Please reopen if the problem persists.
