### ISSUE TITLE
Load only the required driver for testing DB connection 

### ISSUE THREAD

**Issue by anupama-pathirage** [wso2/mi-vscode#435]
Moving the isssue https://github.com/wso2-enterprise/mi-language-server/issues/151 by [thuva9872](https://github.com/thuva9872)

**Description:**

Currently the test db connection method loads all the drivers in the specified version without checking the driver name as the jar name may change for each driver. This logic need to be improved to load only to load the exact driver that is required.

https://github.com/wso2-enterprise/mi-language-server/blob/152e9cfc727fbabcc6948b174a2992da50381c65/org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/customservice/synapse/db/DBConnectionTester.java#L129

<img width="1077" alt="image" src="https://github.com/user-attachments/assets/1e2731d6-b4e9-4bdf-8a34-4f95a712e7aa">

**Comment by ChinthakaJ98** [comment]
The latest release v1.1.1 has resolved this issue. Please reopen if the problem persists.
