### ISSUE TITLE
Proxy diagram breaks when named insequence is added

### ISSUE THREAD

**Issue by kaumini** [wso2/mi-vscode#436]
**Description:**
Proxy diagram breaks when named insequence is added

**Steps to reproduce:**

https://github.com/user-attachments/assets/3442b3e1-06de-482d-934c-3ec4553cc119

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by ChinthakaJ98** [comment]
The latest release v1.1.3 has resolved this issue. Please reopen if the problem persists.
