### ISSUE TITLE
Issues in the Externals endpoint section

### ISSUE THREAD

**Issue by ChinthakaJ98** [wso2/mi-vscode#437]
Below issues need to be fixed.

- [ ] When an endpoint is selected, the call mediator must have that value selected as the endpoint name and that field need to be disabled.
- [ ] In the form that opens it would be better to use the term "Add" instead of "Submit" as the button content.

https://github.com/user-attachments/assets/dc2bdd20-30e1-4835-a81f-a342923bf191

**Comment by kaumini** [comment]
This issue will no longer be reproducible since the endpoints section of externals is removed.
