### ISSUE TITLE
Placeholders for Name and Value fields in the Parameters section in Message Processor forms are not disabled

### ISSUE THREAD

**Issue by ShammiL** [wso2/mi-vscode#438]
**Description:**

<img width="845" alt="image" src="https://github.com/user-attachments/assets/029b9670-2cfb-40dd-a5be-8c64a09c43fa">
Placeholders for Name and Value fields in the Parameters section in Message Processor forms are not disabled by default. Users will have to remove the placeholder text before entering correct values

**Describe your problem(s)**

**Describe your solution(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by ChinthakaJ98** [comment]
The latest release v1.1.3 has resolved this issue. Please reopen if the problem persists.
