### ISSUE TITLE
Extension does not provide a source view for local entries

### ISSUE THREAD

**Issue by ShammiL** [wso2/mi-vscode#443]
**Description:**
Unlike other resources, users can't view the source of a local entry.

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by ChinthakaJ98** [comment]
The latest release v1.1.1 has resolved this issue. Please reopen if the problem persists.
