### ISSUE TITLE
Service catalog is not working properly for versioned API

### ISSUE THREAD

**Issue by SanojPunchihewa** [wso2/mi-vscode#447]
**Description:**

For APIs created without a version, the service catalog works without any issue. However when we specify a version, the service catalog will fail during CAR deployment.

**Comment by SanojPunchihewa** [comment]
Once the car plugin is released we need to update the VSCode plugin as well.

**Comment by SanojPunchihewa** [comment]
`vscode-car-plugin` version `5.2.74` is released with the above fix. @ChinthakaJ98 please do the needful in MI VSCode extension

**Comment by ChinthakaJ98** [comment]
The latest release v1.1.3 has resolved this issue. Please reopen if the problem persists.
