### ISSUE TITLE
Session timeout property is not available for load balance endpoint

### ISSUE THREAD

**Issue by chanikag** [wso2/mi-vscode#458]
**Description:**

<img width="645" alt="Screenshot 2024-10-09 at 8 30 39 AM" src="https://github.com/user-attachments/assets/bbbf2f62-4d5a-4a34-b517-4bdf0f0036ff">

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by ChinthakaJ98** [comment]
The session timeout property will be displayed only if session management is set to any other value other than 'None'. Therefore closing this issue as it is the intended behaviour and it is not a bug.
