### ISSUE TITLE
Datamapper crashes when opening

### ISSUE THREAD

**Issue by KCSAbeywickrama** [wso2/mi-vscode#460]
**Description:**
When opening a datamapper it crashes with the following error message. 
**Additionally, it only happens in VS Code(Tested with v1.93.0). It works fine in Cursor(Tested with v0.40.4).**
![image](https://github.com/user-attachments/assets/1e59e04f-f067-4110-85e3-98c0f7dc7436)

**Additional Info:**
Disconnect from the internet and check the developer tools console, similar error message can be seen even though it not crashes

**Affected Versions:**
v.1.1.1

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**
Priority/Highest, Sevirity/Blocker

**Suggested Assignees (optional):**
@YasanPunch

**Comment by gigara** [comment]
This issue has been fixed with the latest release. Please re-open if persists.
