### ISSUE TITLE
The MI extension landing page pops up for non-MI projects

### ISSUE THREAD

**Issue by ShammiL** [wso2/mi-vscode#461]
**Description:**
The MI extension landing page appears in the following scenarios when users have non-MI-related projects or XML files open:

- When a user creates an XML file that is not part of an MI project.
- When a user reloads the window with XML files from a non-MI project open.

This behaviour occurs only once after the VS Code window is loaded and will only reoccur if the window is reloaded again.

<img width="1497" alt="image" src="https://github.com/user-attachments/assets/142a0f10-a586-4a3c-ad4a-769197912df1">

https://github.com/user-attachments/assets/9d40772e-9f6b-4441-9fc9-8f2a2bd95974

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by thuva9872** [comment]
Duplicate: https://github.com/wso2/mi-vscode/issues/279
