### ISSUE TITLE
Creating and opening a new MI project in the same VSCode window doesn't work properly

### ISSUE THREAD

**Issue by ShammiL** [wso2/mi-vscode#48]
**Description:**
If a new project is created in a VSCode window with an old MI project already open, and then open it in the same window instead of a new one, the new project won't properly load. 
![image](https://github.com/wso2/mi-vscode/assets/47134017/ae210f42-949c-41e7-829f-c71aea7d11ee)
In the above image **websocketEndpoint** is the old project while **wsdlEndpint** is the new one. 
The new project doesn't show any of the components as it should.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by thuva9872** [comment]
Currently, opening multiple projects in the same window is not supported, but this feature will be added in a future update.

**Comment by ChinthakaJ98** [comment]
This issue will be further tracked via https://github.com/wso2/mi-vscode/issues/149 as they are mentioning the same concern.
