### ISSUE TITLE
Connector parameters are not rendered. 

### ISSUE THREAD

**Issue by sameeragunarathne** [wso2/mi-vscode#5]
**Description:**
When using a connector without the UI schema it seems the UI form is not loading with the connector parameters. 
<img width="1728" alt="Screenshot 2024-05-29 at 10 28 39" src="https://github.com/wso2/mi-vscode/assets/5234677/335adae5-d293-4a84-9fac-7a82abfb9a75">

Please find the connector used attached.
[fhirBase-r4-connector-4.2.0.1-SNAPSHOT.zip](https://github.com/wso2/mi-vscode/files/15479106/fhirBase-r4-connector-4.2.0.1-SNAPSHOT.zip)

**Suggested Labels:**

Bug

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
Import the provided connector and use fhirEngageTemplate operation.

**Related Issues:**

**Comment by sameeragunarathne** [comment]
Seems this is still present in v0.9.24062409 (pre-release).

**Comment by kaumini** [comment]
This issue is fixed in the pre release version in vscode marketplace.
