### ISSUE TITLE
Jms message store configuration only allows http url

### ISSUE THREAD

**Issue by kalaiyarasiganeshalingam** [wso2/mi-vscode#52]
**Description:**
<img width="910" alt="Screenshot 2024-07-04 at 16 25 15" src="https://github.com/wso2/mi-vscode/assets/12771261/75c88cdb-f86a-46a9-81cd-2d90b71b2ee1">

**Comment by thuva9872** [comment]
The latest release v1.0.5 has resolved the issue. Please reopen if the problem persists.
