### ISSUE TITLE
Remove `to` field from the `task` creation form

### ISSUE THREAD

**Issue by poorna2152** [wso2/mi-vscode#53]
**Description:**
The `to` field in the task creation form https://ei.docs.wso2.com/en/latest/micro-integrator/references/synapse-properties/scheduled-task-properties/#task-implementation-properties based on this documentation, ` message directly to the endpoint through the main sequence,`. But the `main` sequence is no longer used. And this should be removed. Also the `Message inject destination` field in the form shows `main` as a option which is also invalid and should be removed.

**Comment by ChinthakaJ98** [comment]
Hi @poorna2152,

Why is the main sequence no longer used?

**Comment by poorna2152** [comment]
When we inject the message to an endpoint, it goes through "main" sequence. In MI, the default main sequence is different from older EI versions. Hence the message is not properly getting injected to the endpoint. Since we have a way to send a message to an endpoint via a sequence, removing the 'To' field is better to avoid confusion.
