### ISSUE TITLE
Error is thrown when a sequence with name other than `main` is used for a sequence referenced by the task

### ISSUE THREAD

**Issue by poorna2152** [wso2/mi-vscode#54]
**Description:**
For a scheduled task when the `Message inject destination` is set to a `sequence` and a sequence with a name other than `main` is used an error is thrown when running the code. However when the name `main` is used for the sequence name the code works fine.

**Comment by thuva9872** [comment]
MI is working fine with any existing sequence name. Hence closing this issue.
