### ISSUE TITLE
New expression editor not available in param manager

### ISSUE THREAD

**Issue by SanojPunchihewa** [wso2/mi-vscode#550]
### Description

The param manager still has the old expressions. It does not show the new expression editor

<img width="395" alt="Screenshot 2024-12-17 at 10 11 14" src="https://github.com/user-attachments/assets/569c36e5-52e7-4c2b-9c76-90c6a95e66b8" />

### Steps to Reproduce

Try to add `Additional Parameters` for the Log mediator

### Version

v1.1.624121618 - Pre-alpha

**Comment by YasithD** [comment]
Closing the issue as this is fixed.
