### ISSUE TITLE
Expression only field allow the user to disable EX button

### ISSUE THREAD

**Issue by SanojPunchihewa** [wso2/mi-vscode#555]
### Description

When we have an expression only field, previously the `EX` option was enabled by default and cannot be disabled by clicking on it. However with the new expression support, the `EX` option can be disabled.

### Steps to Reproduce

Use a switch mediator and check the `Expression` field.

### Version

v1.1.624121618 - Pre-alpha

**Comment by YasithD** [comment]
Closing the issue as this is fixed.
