### ISSUE TITLE
Incorrect Username and Password in deployment.toml Do Not Show a Response

### ISSUE THREAD

**Issue by KalinduGandara** [wso2/mi-vscode#58]
**Description:**
When deployment.toml doesn't have the default username and password ("admin"), the Runtime Services tab keeps spinning without displaying an error.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by gigara** [comment]
The latest pre-release v0.9.24072507 has resolved the issue. Please reopen if the problem persists.
