### ISSUE TITLE
Error rendering connector form

### ISSUE THREAD

**Issue by sameeragunarathne** [wso2/mi-vscode#6]
**Description:**

I'm using a connector exported from file system and when loading form for the operations I'm getting following screen.

<img width="1728" alt="Screenshot 2024-05-29 at 10 04 58" src="https://github.com/wso2/mi-vscode/assets/5234677/68e3f438-d10b-442e-9534-5d7260fe14e3">

Please find the attached connector. 
[fhirBundle-r4-connector-4.0.0.zip](https://github.com/wso2/mi-vscode/files/15479126/fhirBundle-r4-connector-4.0.0.zip)

**Suggested Labels:**

Bug

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
Import the connector and use create operation.

**Related Issues:**

**Comment by gigara** [comment]
@sameeragunarathne can you check this with the latest release and confirm?

**Comment by sameeragunarathne** [comment]
@gigara seems this is fixed now. You can close the ticket
