### ISSUE TITLE
Add support for Service Catalog

### ISSUE THREAD

**Issue by YasithD** [wso2/mi-vscode#61]
**Description:**
Currently the OpenAPI definitions, which are generated or reused (when it is used to create the API) are stored in the directory `resources/api-definitions`. While this is a good place to store these files thinking from an user point of view, the MI server expects files to be in a certain format (two files **_swagger** and **_metadata** per each API) which is stored in the `resources/metadata` directory to provide APIM support through the Service Catalog.

We should rethink this experience and try to get users towards the `resource/api-definitions` structure while providing the necessary APIM support. This will include things such as,
- Ideal ways to store the **_swagger** and **_metadata** files.
- Ideal ways to version the swaggers.
- A way to link the API to the swagger.
- Generating missing swaggers at build time, etc.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by ChinthakaJ98** [comment]
This issue will be further tracked via https://github.com/wso2/mi-vscode/issues/332 as they mention the same concern.
