### ISSUE TITLE
Manual Addition of Parameters Required When Using Connector Methods

### ISSUE THREAD

**Issue by kalaiyarasiganeshalingam** [wso2/mi-vscode#67]
**Description:**
When adding any of the connector methods, the function's parameters need to be added manually. This results in inefficiencies and potential errors during the implementation process. Proper automation or default parameter inclusion should be considered to streamline the workflow and reduce manual effort.

**Comment by kaumini** [comment]
Duplicate issue: https://github.com/wso2/mi-vscode/issues/87

**Comment by kaumini** [comment]
This issue is fixed in the pre release version in vscode marketplace.
