### ISSUE TITLE
UI for adding parameter is not aligning the content properly when value of parameter is long

### ISSUE THREAD

**Issue by kalaiyarasiganeshalingam** [wso2/mi-vscode#68]
**Description:**
<img width="536" alt="Screenshot 2024-07-09 at 12 03 06" src="https://github.com/wso2/mi-vscode/assets/12771261/9125ade7-9022-4624-8664-cbe1b76e2751">

**Comment by thuva9872** [comment]
The latest release v1.0.4 has resolved the issue. Please reopen if the problem persists.
