### ISSUE TITLE
Implement MI Automation Mode in VSCode 

### ISSUE THREAD

**Issue by rosensilva** [wso2/mi-vscode#69]
**Description:**
Users should be able to select a sequence to mark as automation mode default sequence
<img width="1717" alt="Screenshot 2024-07-09 at 15 15 11" src="https://github.com/wso2/mi-vscode/assets/13344872/6f34d7e0-7913-4df6-aba8-a9b9ab0e5737">

Also, the VSCode CAR app maven plugin should add the metadata artifacts to the CAPP

**Comment by hevayo** [comment]
Shouldn't the default option of a task should be this ?
