### ISSUE TITLE
Cannot add Response mediator to Aggregate mediator

### ISSUE THREAD

**Issue by wggihan** [wso2/mi-vscode#7]
**Description:**
The response mediator is unavailable from the mediator plate to add to the Aggregate mediator's on complete.

<img width="1168" alt="missing response" src="https://github.com/wso2/mi-vscode/assets/2101222/e0054010-6bd6-4a2c-bdaa-4a51d29f5e8c">

**Affected Product Version:**
v0.9.24053014 (pre-release)

**Comment by isudana** [comment]
Can we close this? anything pending?
