### ISSUE TITLE
Metadata files not getting created

### ISSUE THREAD

**Issue by DinithiDiaz** [wso2/mi-vscode#70]
**Description:**
When we create an API artifact, the metadata files are not created inside the `metadata` folder.

<img width="40%" alt="metadata" src="https://github.com/wso2/mi-vscode/assets/33226735/68167743-bc76-4cb6-be17-59de260ae60c">

---

**MI for VS Code Extension Version:** v0.9.24062409 (pre-release)

---

**Steps to reproduce:**
1. Create an integration project.
2. Create a REST API with the required details.
3. Switch to the VS Code explorer view.
4. Locate the metadata folder.

---

**Doc Issue:** https://github.com/wso2/docs-mi/issues/406

**Comment by SanojPunchihewa** [comment]
Since we can derive the metadata need for the service catalog, we have improved the CAR plugin to generate them during project building via https://github.com/wso2/maven-tools/pull/135
