### ISSUE TITLE
Concerns regarding the Inbound EP Form

### ISSUE THREAD

**Issue by DinithiDiaz** [wso2/mi-vscode#72]
**Description:**
1. When creating a new Inbound Endpoint using the integration studio, the **main sequence** and **error sequence** are mandatory fields only for some of the inbound endpoint types excluding HTTP, HTTPS, Feed, and CXF_WS_RM types. But in MI for VS Code plugin, in the **Inbound EP Form**, Sequence and Error Sequence fields are marked as required for all types. Is this the expected scenario?

    <img width="1100" alt="create-inbound-ep-form" src="https://github.com/wso2/mi-vscode/assets/33226735/f5565eb7-891f-4936-8c87-07040d4b5f8d">

2. In the integration studio, there is a field to generate the sequence and error sequence. This is not available in the MI for VS Code plugin.

    ![new-inbound-endpoint-wizard-2-2](https://github.com/wso2/mi-vscode/assets/33226735/d679e456-c788-481b-9e86-b2c136d8c8c8)

---

**MI for VS Code Extension Version:** v0.9.24062409 (pre-release)

---

**Doc Issue:** https://github.com/wso2/docs-mi/issues/408

**Comment by SanojPunchihewa** [comment]
Main sequence and error sequence are mandatory for all inbound endpoints. MI VSCode v1.0.5 has the option to automatically generate those sequences as well. Closing this as both issues are resolved.
