### ISSUE TITLE
Deprecated outSequence added when creating a proxy service through the VSCode plugin

### ISSUE THREAD

**Issue by ShammiL** [wso2/mi-vscode#73]
**Description:**
When using the VSCode plugin to create a proxy service, the initial code of the proxy service will contain the deprecated `outSequence` 

![image](https://github.com/wso2/mi-vscode/assets/47134017/40166097-b4bb-45b0-a038-6483cbf736fc)

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by ChinthakaJ98** [comment]
The latest release v1.1.1 has resolved this issue. Please reopen if the problem persists.
