### ISSUE TITLE
Flie connector's checkExist operation does not have the configuration UI

### ISSUE THREAD

**Issue by kalaiyarasiganeshalingam** [wso2/mi-vscode#81]
**Description:**
When adding `checklExist` operation using vs code, it does not go to the configuration UI. It goes to the add parameter UI.

<img width="439" alt="Screenshot 2024-07-10 at 14 39 43" src="https://github.com/wso2/mi-vscode/assets/12771261/5adb2cfd-6060-4274-857e-e5d4c31bb6db">

Expected like this:

<img width="426" alt="Screenshot 2024-07-10 at 14 41 42" src="https://github.com/wso2/mi-vscode/assets/12771261/9e0e063c-c115-4ab1-998c-667b235fd89a">

**Comment by kaumini** [comment]
This issue is fixed in the pre release version in vscode marketplace.
