### ISSUE TITLE
Entries of 'Add Parameter' palette are not aligned properly when they are lengthy

### ISSUE THREAD

**Issue by gabilang** [wso2/mi-vscode#88]
**Description:**

$title

<img width="1262" alt="Screenshot 2024-07-11 at 13 01 39" src="https://github.com/wso2/mi-vscode/assets/35595065/303cc126-73f3-48f9-87cf-b1b4b319442f">

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by gabilang** [comment]
<img width="1149" alt="Screenshot 2024-07-11 at 13 41 34" src="https://github.com/user-attachments/assets/70ab660a-cd27-405c-a81b-4d0b56d88207">

Key and values are overlapping if the key exceeds the certain length.

**Comment by gigara** [comment]
The latest pre-release v0.9.24072507 has resolved the issue. Please reopen if the problem persists.
