### ISSUE TITLE
Creating new project opens an existing project

### ISSUE THREAD

**Issue by DinithiDiaz** [wso2/mi-vscode#90]
**Description:**

When we create a new project with a given name in a specific location, if there is already a project with the **same name** in the **same location**, the existing project will be opened. 

But ideally the user should receive an alert indicating that a project with the same name already exists in this location.

**MI for VS Code Extension Version:** v0.9.24062409 (pre-release)

**Steps to reproduce:**

A screen recording is attached below.

https://github.com/wso2/mi-vscode/assets/33226735/65b82d79-ad03-4b79-8cf7-e005189ed03f

**Comment by gigara** [comment]
We should scan the dir for the existing folder when the user selects the directory and block the button based on availability.

**Comment by ChinthakaJ98** [comment]
Closing this issue as it has been fixed in the latest release. 

<img width="1341" alt="Screenshot 2024-08-05 at 11 37 29" src="https://github.com/user-attachments/assets/94917bcc-170f-4e79-840c-4e653930e2c3">
