### ISSUE TITLE
Custom Inbound Endpoint has 'org.wso2.carbon.inbound.kafka.KafkaMessageConsumer' as default for the 'class' field

### ISSUE THREAD

**Issue by gabilang** [wso2/mi-vscode#93]
**Description:**

$title
It seems irrelevant to provide that particular class as a default value. 
If it has been added as an example format, we can use the placeholder text (something like provided for `Name`)

<img width="1136" alt="Screenshot 2024-07-15 at 14 49 11" src="https://github.com/user-attachments/assets/e3d05d9d-8f60-440c-a622-4ab42d7fa0b6">

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by gabilang** [comment]
Placeholder texts can be used for the parameter entries as well. 
<img width="914" alt="Screenshot 2024-07-15 at 15 46 51" src="https://github.com/user-attachments/assets/294838f5-a275-43e5-a883-5b41b9fb1576">

**Comment by hevayo** [comment]
Issue is no longer relevent
