### ISSUE TITLE
Sample projects always opening in a new window

### ISSUE THREAD

**Issue by DinithiDiaz** [wso2/mi-vscode#94]
**Description:**

When we open a sample from the Welcome to MI interface, the sample integration project opens in a new window, even if no other project is open.

Instead, the user should be prompted with a dialog box to choose whether to open it in the same window or a new one.

---

MI for VS Code Extension Version: v0.9.24071508 (pre-release), v0.9.24072507 (pre-release)

---

**Steps to reproduce:**

A screen recording is attached below.

https://github.com/user-attachments/assets/2729c798-b22b-4928-bb33-a05ca5222b07

**Comment by gigara** [comment]
The latest release v1.1.0 has resolved the issue. Please reopen if the problem persists.
